// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TPDojo;

#nullable disable

namespace TPDojo.Migrations
{
    [DbContext(typeof(DojoDbContext))]
    [Migration("20230823090220_ArtMartialSamouraiAddEntityKey")]
    partial class ArtMartialSamouraiAddEntityKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BO.Arme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Degat")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Arme");
                });

            modelBuilder.Entity("BO.ArtMartial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ArtMartial");
                });

            modelBuilder.Entity("BO.ArtMartialSamourai", b =>
                {
                    b.Property<int>("ArtMartialId")
                        .HasColumnType("int");

                    b.Property<int>("SamouraiId")
                        .HasColumnType("int");

                    b.HasKey("ArtMartialId", "SamouraiId");

                    b.HasIndex("SamouraiId");

                    b.ToTable("ArtMartialSamourai");
                });

            modelBuilder.Entity("BO.Samourai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArmeId")
                        .HasColumnType("int");

                    b.Property<int>("Force")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArmeId");

                    b.ToTable("Samourai");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Force = 920,
                            Name = "Abe Masakatsu"
                        },
                        new
                        {
                            Id = 2,
                            Force = 772,
                            Name = "Adachi Yasumori"
                        },
                        new
                        {
                            Id = 3,
                            Force = 632,
                            Name = "Adachi Kagemori"
                        },
                        new
                        {
                            Id = 4,
                            Force = 1489,
                            Name = "Adams William"
                        },
                        new
                        {
                            Id = 5,
                            Force = 1483,
                            Name = "Aiou Mototsuna"
                        },
                        new
                        {
                            Id = 6,
                            Force = 239,
                            Name = "Akai Terukage"
                        },
                        new
                        {
                            Id = 7,
                            Force = 1932,
                            Name = "Akao Kiyotsuna"
                        },
                        new
                        {
                            Id = 8,
                            Force = 773,
                            Name = "Akechi Mitsuhide"
                        },
                        new
                        {
                            Id = 9,
                            Force = 1489,
                            Name = "Akiyama Nobutomo"
                        },
                        new
                        {
                            Id = 10,
                            Force = 89,
                            Name = "Amago Haruhisa"
                        },
                        new
                        {
                            Id = 11,
                            Force = 1071,
                            Name = "Amago Yoshihisa"
                        },
                        new
                        {
                            Id = 12,
                            Force = 1382,
                            Name = "Andō Morinari"
                        },
                        new
                        {
                            Id = 13,
                            Force = 1062,
                            Name = "Ankokuji Ekei"
                        },
                        new
                        {
                            Id = 14,
                            Force = 394,
                            Name = "Aochi Shigetsuna"
                        },
                        new
                        {
                            Id = 15,
                            Force = 658,
                            Name = "Aokage Takaakira"
                        },
                        new
                        {
                            Id = 16,
                            Force = 1590,
                            Name = "Aoki Kazushige"
                        },
                        new
                        {
                            Id = 17,
                            Force = 122,
                            Name = "Akahori Chohichi"
                        },
                        new
                        {
                            Id = 18,
                            Force = 540,
                            Name = "Arai Hakuseki"
                        },
                        new
                        {
                            Id = 19,
                            Force = 1686,
                            Name = "Araki Motokiyo"
                        },
                        new
                        {
                            Id = 20,
                            Force = 1969,
                            Name = "Araki Murashige"
                        },
                        new
                        {
                            Id = 21,
                            Force = 1757,
                            Name = "Araki Muratsugu"
                        },
                        new
                        {
                            Id = 22,
                            Force = 1102,
                            Name = "Arima Kihei"
                        },
                        new
                        {
                            Id = 23,
                            Force = 1357,
                            Name = "Asakura Yoshikage"
                        },
                        new
                        {
                            Id = 24,
                            Force = 538,
                            Name = "Ayame Kagekatsu"
                        },
                        new
                        {
                            Id = 25,
                            Force = 1822,
                            Name = "Azai Hisamasa"
                        },
                        new
                        {
                            Id = 26,
                            Force = 1073,
                            Name = "Azai Nagamasa"
                        },
                        new
                        {
                            Id = 27,
                            Force = 1975,
                            Name = "Azai Sukemasa"
                        },
                        new
                        {
                            Id = 28,
                            Force = 195,
                            Name = "Baba Nobufusa"
                        },
                        new
                        {
                            Id = 29,
                            Force = 1221,
                            Name = "Bessho Nagaharu"
                        },
                        new
                        {
                            Id = 30,
                            Force = 1989,
                            Name = "Chacha"
                        },
                        new
                        {
                            Id = 31,
                            Force = 1126,
                            Name = "Chiba Shusaku Narimasa"
                        },
                        new
                        {
                            Id = 32,
                            Force = 195,
                            Name = "Chōsokabe Morichika"
                        },
                        new
                        {
                            Id = 33,
                            Force = 1663,
                            Name = "Chōsokabe Kunichika"
                        },
                        new
                        {
                            Id = 34,
                            Force = 1010,
                            Name = "Chōsokabe Motochika"
                        },
                        new
                        {
                            Id = 35,
                            Force = 555,
                            Name = "Chōsokabe Nobuchika"
                        },
                        new
                        {
                            Id = 36,
                            Force = 510,
                            Name = "Collache Eugène"
                        },
                        new
                        {
                            Id = 37,
                            Force = 1009,
                            Name = "Date Masamune"
                        },
                        new
                        {
                            Id = 38,
                            Force = 1489,
                            Name = "Date Shigezane"
                        },
                        new
                        {
                            Id = 39,
                            Force = 1566,
                            Name = "Doi Toshikatsu"
                        },
                        new
                        {
                            Id = 40,
                            Force = 1622,
                            Name = "Etō Shinpei"
                        },
                        new
                        {
                            Id = 41,
                            Force = 755,
                            Name = "Endō Naotsune"
                        },
                        new
                        {
                            Id = 42,
                            Force = 808,
                            Name = "Enjoji Nobutane"
                        },
                        new
                        {
                            Id = 43,
                            Force = 1626,
                            Name = "ENameoto Takeaki"
                        },
                        new
                        {
                            Id = 44,
                            Force = 662,
                            Name = "Era Fusahide"
                        },
                        new
                        {
                            Id = 45,
                            Force = 1537,
                            Name = "Fūma Kotarō"
                        },
                        new
                        {
                            Id = 46,
                            Force = 248,
                            Name = "Fuwa Mitsuharu"
                        },
                        new
                        {
                            Id = 47,
                            Force = 1970,
                            Name = "Fukushima Masanori"
                        },
                        new
                        {
                            Id = 48,
                            Force = 143,
                            Name = "Gamō Katahide"
                        },
                        new
                        {
                            Id = 49,
                            Force = 915,
                            Name = "Gamō Ujisato"
                        },
                        new
                        {
                            Id = 50,
                            Force = 1597,
                            Name = "Harada Naomasa"
                        },
                        new
                        {
                            Id = 51,
                            Force = 1840,
                            Name = "Harada Nobutane"
                        },
                        new
                        {
                            Id = 52,
                            Force = 1700,
                            Name = "Harada Sanosuke"
                        },
                        new
                        {
                            Id = 53,
                            Force = 1849,
                            Name = "Hasekura Tsunenaga"
                        },
                        new
                        {
                            Id = 54,
                            Force = 299,
                            Name = "Hattori Hanzō"
                        },
                        new
                        {
                            Id = 55,
                            Force = 1821,
                            Name = "Hatano Hideharu"
                        },
                        new
                        {
                            Id = 56,
                            Force = 660,
                            Name = "Hasegawa Eishin"
                        },
                        new
                        {
                            Id = 57,
                            Force = 1144,
                            Name = "Hayashizaki Jinsuke Shigenobu"
                        },
                        new
                        {
                            Id = 58,
                            Force = 882,
                            Name = "Hayashi Narinaga"
                        },
                        new
                        {
                            Id = 59,
                            Force = 1424,
                            Name = "Hijikata Toshizo"
                        },
                        new
                        {
                            Id = 60,
                            Force = 167,
                            Name = "Hirate Masahide"
                        },
                        new
                        {
                            Id = 61,
                            Force = 489,
                            Name = "Hitotsubashi Keiki"
                        },
                        new
                        {
                            Id = 62,
                            Force = 1525,
                            Name = "Hōjō Masako"
                        },
                        new
                        {
                            Id = 63,
                            Force = 498,
                            Name = "Hōjō Tokimune"
                        },
                        new
                        {
                            Id = 64,
                            Force = 1732,
                            Name = "Hōjō Ujiyasu"
                        },
                        new
                        {
                            Id = 65,
                            Force = 685,
                            Name = "Hōjō Ujimasa"
                        },
                        new
                        {
                            Id = 66,
                            Force = 676,
                            Name = "Honda Tadakatsu"
                        },
                        new
                        {
                            Id = 67,
                            Force = 924,
                            Name = "Honda Tadatomo"
                        },
                        new
                        {
                            Id = 68,
                            Force = 842,
                            Name = "Honganji Kennyo"
                        },
                        new
                        {
                            Id = 69,
                            Force = 1048,
                            Name = "Horio Yoshiharu"
                        },
                        new
                        {
                            Id = 70,
                            Force = 1570,
                            Name = "Hosokawa Fujitaka"
                        },
                        new
                        {
                            Id = 71,
                            Force = 1943,
                            Name = "Hosokawa Gracia"
                        },
                        new
                        {
                            Id = 72,
                            Force = 62,
                            Name = "Hosokawa Tadaoki"
                        },
                        new
                        {
                            Id = 73,
                            Force = 1303,
                            Name = "Hotta Masatoshi"
                        },
                        new
                        {
                            Id = 74,
                            Force = 1875,
                            Name = "Ii Naoaki"
                        },
                        new
                        {
                            Id = 75,
                            Force = 1751,
                            Name = "Ii Naomasa"
                        },
                        new
                        {
                            Id = 76,
                            Force = 699,
                            Name = "Ii Naomori"
                        },
                        new
                        {
                            Id = 77,
                            Force = 1562,
                            Name = "Ii Naonaka"
                        },
                        new
                        {
                            Id = 78,
                            Force = 550,
                            Name = "Ii Naosuke"
                        },
                        new
                        {
                            Id = 79,
                            Force = 1444,
                            Name = "Ii Naotaka"
                        },
                        new
                        {
                            Id = 80,
                            Force = 1883,
                            Name = "Ii Naotora"
                        },
                        new
                        {
                            Id = 81,
                            Force = 885,
                            Name = "Ii Naoyuki"
                        },
                        new
                        {
                            Id = 82,
                            Force = 1161,
                            Name = "Ii Naozumi"
                        },
                        new
                        {
                            Id = 83,
                            Force = 1914,
                            Name = "Iizasa Ienao"
                        },
                        new
                        {
                            Id = 84,
                            Force = 981,
                            Name = "Ijuin Tadaaki"
                        },
                        new
                        {
                            Id = 85,
                            Force = 1989,
                            Name = "Ikeda Tsuneoki"
                        },
                        new
                        {
                            Id = 86,
                            Force = 1587,
                            Name = "Imagawa Ujizane"
                        },
                        new
                        {
                            Id = 87,
                            Force = 1023,
                            Name = "Imagawa Yoshimoto"
                        },
                        new
                        {
                            Id = 88,
                            Force = 1957,
                            Name = "Imai Kanehira"
                        },
                        new
                        {
                            Id = 89,
                            Force = 642,
                            Name = "Inaba Yoshimichi"
                        },
                        new
                        {
                            Id = 90,
                            Force = 220,
                            Name = "Inugami Nagayasu"
                        },
                        new
                        {
                            Id = 91,
                            Force = 930,
                            Name = "Ishida Mitsunari"
                        },
                        new
                        {
                            Id = 92,
                            Force = 500,
                            Name = "Isshiki Fujinaga"
                        },
                        new
                        {
                            Id = 93,
                            Force = 1875,
                            Name = "Itagaki Nobukata"
                        },
                        new
                        {
                            Id = 94,
                            Force = 988,
                            Name = "Itō Hirobumi"
                        },
                        new
                        {
                            Id = 95,
                            Force = 767,
                            Name = "Iwanari Tomomichi"
                        },
                        new
                        {
                            Id = 96,
                            Force = 701,
                            Name = "Jinbo Nagamoto"
                        },
                        new
                        {
                            Id = 97,
                            Force = 1787,
                            Name = "Jonas Tönse"
                        },
                        new
                        {
                            Id = 98,
                            Force = 1392,
                            Name = "Kannan Kumar(Salem)"
                        },
                        new
                        {
                            Id = 99,
                            Force = 1784,
                            Name = "Kakeda Toshimune"
                        },
                        new
                        {
                            Id = 100,
                            Force = 306,
                            Name = "Kaneko Ietada"
                        },
                        new
                        {
                            Id = 101,
                            Force = 1041,
                            Name = "Katagiri Katsumoto"
                        },
                        new
                        {
                            Id = 102,
                            Force = 630,
                            Name = "Katakura Kojūro"
                        },
                        new
                        {
                            Id = 103,
                            Force = 246,
                            Name = "Katakura Shigenaga"
                        },
                        new
                        {
                            Id = 104,
                            Force = 1562,
                            Name = "Kataoka Mitsumasa"
                        },
                        new
                        {
                            Id = 105,
                            Force = 1349,
                            Name = "Katō Kiyomasa"
                        },
                        new
                        {
                            Id = 106,
                            Force = 822,
                            Name = "Kawakami Gensai"
                        },
                        new
                        {
                            Id = 107,
                            Force = 1292,
                            Name = "Kido Takayoshi"
                        },
                        new
                        {
                            Id = 108,
                            Force = 1631,
                            Name = "Kikkawa Hiroie"
                        },
                        new
                        {
                            Id = 109,
                            Force = 1005,
                            Name = "Kimotsuki Kanetsugu"
                        },
                        new
                        {
                            Id = 110,
                            Force = 1488,
                            Name = "Kitamura Kansuke"
                        },
                        new
                        {
                            Id = 111,
                            Force = 867,
                            Name = "Kobayakawa Hideaki"
                        },
                        new
                        {
                            Id = 112,
                            Force = 302,
                            Name = "Kobayakawa Hidekane"
                        },
                        new
                        {
                            Id = 113,
                            Force = 35,
                            Name = "Kobayakawa Takakage"
                        },
                        new
                        {
                            Id = 114,
                            Force = 622,
                            Name = "Konishi Yukinaga"
                        },
                        new
                        {
                            Id = 115,
                            Force = 1951,
                            Name = "Kojima Toyoharu"
                        },
                        new
                        {
                            Id = 116,
                            Force = 1146,
                            Name = "Kuroda Kanbei"
                        },
                        new
                        {
                            Id = 117,
                            Force = 1621,
                            Name = "Kuroda Kiyotaka"
                        },
                        new
                        {
                            Id = 118,
                            Force = 1220,
                            Name = "Kusunoki Masashige"
                        },
                        new
                        {
                            Id = 119,
                            Force = 568,
                            Name = "Kuwana Tarozaemon"
                        },
                        new
                        {
                            Id = 120,
                            Force = 442,
                            Name = "Kumagai Naozane"
                        },
                        new
                        {
                            Id = 121,
                            Force = 956,
                            Name = "Maeda Keiji"
                        },
                        new
                        {
                            Id = 122,
                            Force = 1031,
                            Name = "Maeda Matsu"
                        },
                        new
                        {
                            Id = 123,
                            Force = 210,
                            Name = "Maeda Nagatane"
                        },
                        new
                        {
                            Id = 124,
                            Force = 1310,
                            Name = "Maeda Toshiie"
                        },
                        new
                        {
                            Id = 125,
                            Force = 281,
                            Name = "Maeda Toshinaga"
                        },
                        new
                        {
                            Id = 126,
                            Force = 244,
                            Name = "Maeda Toshitsune"
                        },
                        new
                        {
                            Id = 127,
                            Force = 429,
                            Name = "Magome Kageyu"
                        },
                        new
                        {
                            Id = 128,
                            Force = 1669,
                            Name = "Manabe Akifusa"
                        },
                        new
                        {
                            Id = 129,
                            Force = 1741,
                            Name = "Matsudaira Katamori"
                        },
                        new
                        {
                            Id = 130,
                            Force = 1486,
                            Name = "Matsudaira Nobutsuna"
                        },
                        new
                        {
                            Id = 131,
                            Force = 796,
                            Name = "Matsudaira Nobuyasu"
                        },
                        new
                        {
                            Id = 132,
                            Force = 1704,
                            Name = "Matsudaira Higo no Kami Katamori"
                        },
                        new
                        {
                            Id = 133,
                            Force = 447,
                            Name = "Matsudaira Sadanobu"
                        },
                        new
                        {
                            Id = 134,
                            Force = 1208,
                            Name = "Matsudaira Tadayoshi"
                        },
                        new
                        {
                            Id = 135,
                            Force = 1239,
                            Name = "Matsudaira Teru"
                        },
                        new
                        {
                            Id = 136,
                            Force = 1267,
                            Name = "Matsunaga Hisahide"
                        },
                        new
                        {
                            Id = 137,
                            Force = 1405,
                            Name = "Matsunaga Hisamichi"
                        },
                        new
                        {
                            Id = 138,
                            Force = 1477,
                            Name = "Matsuo Bashō"
                        },
                        new
                        {
                            Id = 139,
                            Force = 1971,
                            Name = "Matsudaira Motoyasu"
                        },
                        new
                        {
                            Id = 140,
                            Force = 801,
                            Name = "Minamoto no Mitsunaka"
                        },
                        new
                        {
                            Id = 141,
                            Force = 323,
                            Name = "Minamoto no Yoshiie"
                        },
                        new
                        {
                            Id = 142,
                            Force = 1707,
                            Name = "Minamoto no Yoshimitsu"
                        },
                        new
                        {
                            Id = 143,
                            Force = 446,
                            Name = "Minamoto no Yoshinaka"
                        },
                        new
                        {
                            Id = 144,
                            Force = 1998,
                            Name = "Minamoto no Yoshitomo"
                        },
                        new
                        {
                            Id = 145,
                            Force = 950,
                            Name = "Minamoto no Yoshitsune"
                        },
                        new
                        {
                            Id = 146,
                            Force = 904,
                            Name = "Minamoto no Tameyoshi"
                        },
                        new
                        {
                            Id = 147,
                            Force = 169,
                            Name = "Minamoto no Yorimasa"
                        },
                        new
                        {
                            Id = 148,
                            Force = 1259,
                            Name = "Minamoto no Yorimitsu"
                        },
                        new
                        {
                            Id = 149,
                            Force = 421,
                            Name = "Minamoto no Yoritomo"
                        },
                        new
                        {
                            Id = 150,
                            Force = 1896,
                            Name = "Minamoto no Noriyori"
                        },
                        new
                        {
                            Id = 151,
                            Force = 1581,
                            Name = "Minoro Takashi"
                        },
                        new
                        {
                            Id = 152,
                            Force = 961,
                            Name = "Miura Anjin"
                        },
                        new
                        {
                            Id = 153,
                            Force = 1526,
                            Name = "Miura Yoshimoto"
                        },
                        new
                        {
                            Id = 154,
                            Force = 593,
                            Name = "Miyamoto Musashi"
                        },
                        new
                        {
                            Id = 155,
                            Force = 576,
                            Name = "Miyoshi Chōkei"
                        },
                        new
                        {
                            Id = 156,
                            Force = 292,
                            Name = "Miyoshi Kazuhide"
                        },
                        new
                        {
                            Id = 157,
                            Force = 634,
                            Name = "Miyoshi Masaga"
                        },
                        new
                        {
                            Id = 158,
                            Force = 1353,
                            Name = "Miyoshi Masayasu"
                        },
                        new
                        {
                            Id = 159,
                            Force = 1560,
                            Name = "Miyoshi Moriyata"
                        },
                        new
                        {
                            Id = 160,
                            Force = 336,
                            Name = "Miyoshi Nagayuki"
                        },
                        new
                        {
                            Id = 161,
                            Force = 363,
                            Name = "Miyoshi Yoshitsugu"
                        },
                        new
                        {
                            Id = 162,
                            Force = 880,
                            Name = "Mizuno Tadakuni"
                        },
                        new
                        {
                            Id = 163,
                            Force = 356,
                            Name = "Moniwa Yoshinao"
                        },
                        new
                        {
                            Id = 164,
                            Force = 1657,
                            Name = "Mōri Motonari"
                        },
                        new
                        {
                            Id = 165,
                            Force = 1843,
                            Name = "Mōri Nagasada"
                        },
                        new
                        {
                            Id = 166,
                            Force = 136,
                            Name = "Mori Nagayoshi"
                        },
                        new
                        {
                            Id = 167,
                            Force = 1363,
                            Name = "Mōri Okimoto"
                        },
                        new
                        {
                            Id = 168,
                            Force = 438,
                            Name = "Mori Ranmaru"
                        },
                        new
                        {
                            Id = 169,
                            Force = 617,
                            Name = "Mōri Takamoto"
                        },
                        new
                        {
                            Id = 170,
                            Force = 1496,
                            Name = "Mori Tadamasa"
                        },
                        new
                        {
                            Id = 171,
                            Force = 572,
                            Name = "Mōri Terumoto"
                        },
                        new
                        {
                            Id = 172,
                            Force = 394,
                            Name = "Mori Yoshinari"
                        },
                        new
                        {
                            Id = 173,
                            Force = 1314,
                            Name = "Murai Sadakatsu"
                        },
                        new
                        {
                            Id = 174,
                            Force = 494,
                            Name = "Nagakura Shinpachi"
                        },
                        new
                        {
                            Id = 175,
                            Force = 1415,
                            Name = "Nagao Harukage"
                        },
                        new
                        {
                            Id = 176,
                            Force = 1657,
                            Name = "Nagao Kagenobu"
                        },
                        new
                        {
                            Id = 177,
                            Force = 1774,
                            Name = "Nagao Masakage"
                        },
                        new
                        {
                            Id = 178,
                            Force = 581,
                            Name = "Nagao Tamekage"
                        },
                        new
                        {
                            Id = 179,
                            Force = 1512,
                            Name = "Nakagawa Kiyohide"
                        },
                        new
                        {
                            Id = 180,
                            Force = 741,
                            Name = "Nakaoka Shintarō"
                        },
                        new
                        {
                            Id = 181,
                            Force = 1595,
                            Name = "Naoe Kagetsuna"
                        },
                        new
                        {
                            Id = 182,
                            Force = 499,
                            Name = "Naoe Kanetsugu"
                        },
                        new
                        {
                            Id = 183,
                            Force = 832,
                            Name = "Narita Kaihime"
                        },
                        new
                        {
                            Id = 184,
                            Force = 1312,
                            Name = "Nene"
                        },
                        new
                        {
                            Id = 185,
                            Force = 699,
                            Name = "Nihonmatsu Yoshitsugu"
                        },
                        new
                        {
                            Id = 186,
                            Force = 71,
                            Name = "Niimi Nishiki"
                        },
                        new
                        {
                            Id = 187,
                            Force = 16,
                            Name = "Niiro Tadamoto"
                        },
                        new
                        {
                            Id = 188,
                            Force = 124,
                            Name = "Niwa Nagahide"
                        },
                        new
                        {
                            Id = 189,
                            Force = 1659,
                            Name = "Niwa Nagashige"
                        },
                        new
                        {
                            Id = 190,
                            Force = 1061,
                            Name = "Oda Hiroyoshi"
                        },
                        new
                        {
                            Id = 191,
                            Force = 1820,
                            Name = "Oda Nobuhide"
                        },
                        new
                        {
                            Id = 192,
                            Force = 1521,
                            Name = "Oda Nobukata"
                        },
                        new
                        {
                            Id = 193,
                            Force = 421,
                            Name = "Oda Nobukiyo"
                        },
                        new
                        {
                            Id = 194,
                            Force = 226,
                            Name = "Oda Nobunaga"
                        },
                        new
                        {
                            Id = 195,
                            Force = 1077,
                            Name = "Oda Nobutada"
                        },
                        new
                        {
                            Id = 196,
                            Force = 1027,
                            Name = "Oda Nobutomo"
                        },
                        new
                        {
                            Id = 197,
                            Force = 1015,
                            Name = "Oda Nobukatsu"
                        },
                        new
                        {
                            Id = 198,
                            Force = 421,
                            Name = "Oda Nobuyasu"
                        },
                        new
                        {
                            Id = 199,
                            Force = 1571,
                            Name = "Ogasawara Shōsai"
                        },
                        new
                        {
                            Id = 200,
                            Force = 1946,
                            Name = "Ōishi Kuranosuke"
                        },
                        new
                        {
                            Id = 201,
                            Force = 1775,
                            Name = "Okada Izō"
                        },
                        new
                        {
                            Id = 202,
                            Force = 794,
                            Name = "Judge Ooka"
                        },
                        new
                        {
                            Id = 203,
                            Force = 1824,
                            Name = "Ōta Dōkan"
                        },
                        new
                        {
                            Id = 204,
                            Force = 200,
                            Name = "Ōtani Yoshitsugu"
                        },
                        new
                        {
                            Id = 205,
                            Force = 1621,
                            Name = "Ōtani Yoshiharu"
                        },
                        new
                        {
                            Id = 206,
                            Force = 1549,
                            Name = "Ōtomo Sōrin"
                        },
                        new
                        {
                            Id = 207,
                            Force = 1901,
                            Name = "Okita Sōji"
                        },
                        new
                        {
                            Id = 208,
                            Force = 15,
                            Name = "Ōkubo Toshimichi"
                        },
                        new
                        {
                            Id = 209,
                            Force = 397,
                            Name = "OkuNameiya Masaie"
                        },
                        new
                        {
                            Id = 210,
                            Force = 621,
                            Name = "Ōuchi Yoshitaka"
                        },
                        new
                        {
                            Id = 211,
                            Force = 775,
                            Name = "Omy Yoshika"
                        },
                        new
                        {
                            Id = 212,
                            Force = 1421,
                            Name = "Pore Sufi"
                        },
                        new
                        {
                            Id = 213,
                            Force = 186,
                            Name = "Reizei Takatoyo"
                        },
                        new
                        {
                            Id = 214,
                            Force = 726,
                            Name = "Rokkaku Sadayori"
                        },
                        new
                        {
                            Id = 215,
                            Force = 453,
                            Name = "Rokkaku Yoshiharu"
                        },
                        new
                        {
                            Id = 216,
                            Force = 1488,
                            Name = "Rokkaku Yoshikata"
                        },
                        new
                        {
                            Id = 217,
                            Force = 683,
                            Name = "Rusu Masakage"
                        },
                        new
                        {
                            Id = 218,
                            Force = 1235,
                            Name = "Ryūzōji Takanobu"
                        },
                        new
                        {
                            Id = 219,
                            Force = 1416,
                            Name = "Saigo Kiyokazu"
                        },
                        new
                        {
                            Id = 220,
                            Force = 1678,
                            Name = "Saigō Masako"
                        },
                        new
                        {
                            Id = 221,
                            Force = 1775,
                            Name = "Sagara Taketō"
                        },
                        new
                        {
                            Id = 222,
                            Force = 1649,
                            Name = "Saigō Takamori"
                        },
                        new
                        {
                            Id = 223,
                            Force = 172,
                            Name = "Saigo Yoshikatsu"
                        },
                        new
                        {
                            Id = 224,
                            Force = 645,
                            Name = "Saitō Dōsan"
                        },
                        new
                        {
                            Id = 225,
                            Force = 1810,
                            Name = "Saitō Hajime"
                        },
                        new
                        {
                            Id = 226,
                            Force = 214,
                            Name = "Saito Musashibō Benkei"
                        },
                        new
                        {
                            Id = 227,
                            Force = 122,
                            Name = "Saitō Yoshitatsu"
                        },
                        new
                        {
                            Id = 228,
                            Force = 131,
                            Name = "Sakai Tadakiyo"
                        },
                        new
                        {
                            Id = 229,
                            Force = 1408,
                            Name = "Sakai Tadashige"
                        },
                        new
                        {
                            Id = 230,
                            Force = 1356,
                            Name = "Sakai Tadatsugu"
                        },
                        new
                        {
                            Id = 231,
                            Force = 1828,
                            Name = "Sakai Tadayo"
                        },
                        new
                        {
                            Id = 232,
                            Force = 774,
                            Name = "Sakakibara Yasumasa"
                        },
                        new
                        {
                            Id = 233,
                            Force = 1747,
                            Name = "Sakamoto Ryōma"
                        },
                        new
                        {
                            Id = 234,
                            Force = 1853,
                            Name = "Sakuma Morimasa"
                        },
                        new
                        {
                            Id = 235,
                            Force = 1066,
                            Name = "Sakuma Nobumori"
                        },
                        new
                        {
                            Id = 236,
                            Force = 914,
                            Name = "Sanada Akihime"
                        },
                        new
                        {
                            Id = 237,
                            Force = 1636,
                            Name = "Sanada Komatsuhime"
                        },
                        new
                        {
                            Id = 238,
                            Force = 1117,
                            Name = "Sanada Masayuki"
                        },
                        new
                        {
                            Id = 239,
                            Force = 416,
                            Name = "Sanada Nobuyuki"
                        },
                        new
                        {
                            Id = 240,
                            Force = 1565,
                            Name = "Sanada Yukimura"
                        },
                        new
                        {
                            Id = 241,
                            Force = 1416,
                            Name = "Sasaki Kojirō"
                        },
                        new
                        {
                            Id = 242,
                            Force = 690,
                            Name = "Sassa Narimasa"
                        },
                        new
                        {
                            Id = 243,
                            Force = 768,
                            Name = "Sasuke Sarutobi"
                        },
                        new
                        {
                            Id = 244,
                            Force = 985,
                            Name = "Serizawa Kamo"
                        },
                        new
                        {
                            Id = 245,
                            Force = 1471,
                            Name = "Shibata Katsuie"
                        },
                        new
                        {
                            Id = 246,
                            Force = 1270,
                            Name = "Shima Sakon"
                        },
                        new
                        {
                            Id = 247,
                            Force = 367,
                            Name = "Shimada Ichirō"
                        },
                        new
                        {
                            Id = 248,
                            Force = 992,
                            Name = "Shimazu Katsuhisa"
                        },
                        new
                        {
                            Id = 249,
                            Force = 1378,
                            Name = "Shimazu Tadahisa"
                        },
                        new
                        {
                            Id = 250,
                            Force = 685,
                            Name = "Shimazu Tadatsune"
                        },
                        new
                        {
                            Id = 251,
                            Force = 1115,
                            Name = "Shimazu Tadayoshi"
                        },
                        new
                        {
                            Id = 252,
                            Force = 566,
                            Name = "Shimazu Takahisa"
                        },
                        new
                        {
                            Id = 253,
                            Force = 1171,
                            Name = "Shimazu Toyohisa"
                        },
                        new
                        {
                            Id = 254,
                            Force = 1184,
                            Name = "Shimazu Yoshihiro"
                        },
                        new
                        {
                            Id = 255,
                            Force = 1798,
                            Name = "Shimazu Yoshihisa"
                        },
                        new
                        {
                            Id = 256,
                            Force = 771,
                            Name = "Shindou Hiroshii"
                        },
                        new
                        {
                            Id = 257,
                            Force = 1169,
                            Name = "Sogo Nagayasu"
                        },
                        new
                        {
                            Id = 258,
                            Force = 1298,
                            Name = "Sue Yoshitaka"
                        },
                        new
                        {
                            Id = 259,
                            Force = 913,
                            Name = "Tachibana Muneshige"
                        },
                        new
                        {
                            Id = 260,
                            Force = 1465,
                            Name = "Tachibana Dōsetsu"
                        },
                        new
                        {
                            Id = 261,
                            Force = 1981,
                            Name = "Tachibana Ginchiyo"
                        },
                        new
                        {
                            Id = 262,
                            Force = 1998,
                            Name = "Taigen Sessai"
                        },
                        new
                        {
                            Id = 263,
                            Force = 271,
                            Name = "Taira no Kiyomori"
                        },
                        new
                        {
                            Id = 264,
                            Force = 250,
                            Name = "Taira Masakado"
                        },
                        new
                        {
                            Id = 265,
                            Force = 50,
                            Name = "Takahashi Shigetane"
                        },
                        new
                        {
                            Id = 266,
                            Force = 193,
                            Name = "Takenaka Shigeharu"
                        },
                        new
                        {
                            Id = 267,
                            Force = 265,
                            Name = "Takasugi Shinsaku"
                        },
                        new
                        {
                            Id = 268,
                            Force = 819,
                            Name = "Takayama Justo"
                        },
                        new
                        {
                            Id = 269,
                            Force = 254,
                            Name = "Takayama Ukon"
                        },
                        new
                        {
                            Id = 270,
                            Force = 1380,
                            Name = "Takechi Hanpeita"
                        },
                        new
                        {
                            Id = 271,
                            Force = 105,
                            Name = "Takeda Katsuyori"
                        },
                        new
                        {
                            Id = 272,
                            Force = 1695,
                            Name = "Takeda Nobukatsu"
                        },
                        new
                        {
                            Id = 273,
                            Force = 512,
                            Name = "Takeda Nobushige"
                        },
                        new
                        {
                            Id = 274,
                            Force = 1324,
                            Name = "Takeda Shingen"
                        },
                        new
                        {
                            Id = 275,
                            Force = 913,
                            Name = "Takenaka Hanbei"
                        },
                        new
                        {
                            Id = 276,
                            Force = 580,
                            Name = "Tani Tadasumi"
                        },
                        new
                        {
                            Id = 277,
                            Force = 1713,
                            Name = "Tōdō Takatora"
                        },
                        new
                        {
                            Id = 278,
                            Force = 180,
                            Name = "Toki Yorinari"
                        },
                        new
                        {
                            Id = 279,
                            Force = 806,
                            Name = "Tochimitsu Gantyoki"
                        },
                        new
                        {
                            Id = 280,
                            Force = 1702,
                            Name = "Tokugawa Ieyasu"
                        },
                        new
                        {
                            Id = 281,
                            Force = 1684,
                            Name = "Tokugawa Hidetada"
                        },
                        new
                        {
                            Id = 282,
                            Force = 111,
                            Name = "Tokugawa Nariaki"
                        },
                        new
                        {
                            Id = 283,
                            Force = 236,
                            Name = "Tokugawa Yoshinobu"
                        },
                        new
                        {
                            Id = 284,
                            Force = 306,
                            Name = "Torii Mototada"
                        },
                        new
                        {
                            Id = 285,
                            Force = 395,
                            Name = "Toyotomi Hidenaga"
                        },
                        new
                        {
                            Id = 286,
                            Force = 1007,
                            Name = "Toyotomi Hideyoshi"
                        },
                        new
                        {
                            Id = 287,
                            Force = 121,
                            Name = "Toyotomi Hideyori"
                        },
                        new
                        {
                            Id = 288,
                            Force = 1786,
                            Name = "Tozuka Tadaharu"
                        },
                        new
                        {
                            Id = 289,
                            Force = 1574,
                            Name = "Tsukahara Bokuden"
                        },
                        new
                        {
                            Id = 290,
                            Force = 666,
                            Name = "Uesugi Kagekatsu"
                        },
                        new
                        {
                            Id = 291,
                            Force = 66,
                            Name = "Uesugi Kagetora"
                        },
                        new
                        {
                            Id = 292,
                            Force = 671,
                            Name = "Uesugi Kenshin"
                        },
                        new
                        {
                            Id = 293,
                            Force = 1612,
                            Name = "Ujiie Naotomo"
                        },
                        new
                        {
                            Id = 294,
                            Force = 1129,
                            Name = "Ukita Naoie"
                        },
                        new
                        {
                            Id = 295,
                            Force = 850,
                            Name = "Ukita Okiie"
                        },
                        new
                        {
                            Id = 296,
                            Force = 453,
                            Name = "Umezawa Michiharu"
                        },
                        new
                        {
                            Id = 297,
                            Force = 746,
                            Name = "Usami Sadamitsu"
                        },
                        new
                        {
                            Id = 298,
                            Force = 807,
                            Name = "Uyama Hisanobu"
                        },
                        new
                        {
                            Id = 299,
                            Force = 832,
                            Name = "Wada Shinsuke"
                        },
                        new
                        {
                            Id = 300,
                            Force = 716,
                            Name = "Watanabe Kazan"
                        },
                        new
                        {
                            Id = 301,
                            Force = 1210,
                            Name = "Watanabe no Tsuna"
                        },
                        new
                        {
                            Id = 302,
                            Force = 1230,
                            Name = "Yasumero Kenshin"
                        },
                        new
                        {
                            Id = 303,
                            Force = 652,
                            Name = "Yagyū Jūbei Mitsuyoshi"
                        },
                        new
                        {
                            Id = 304,
                            Force = 876,
                            Name = "Yagyū Munenori"
                        },
                        new
                        {
                            Id = 305,
                            Force = 1803,
                            Name = "Yamauchi Kazutoyo"
                        },
                        new
                        {
                            Id = 306,
                            Force = 867,
                            Name = "Yamada Arinaga"
                        },
                        new
                        {
                            Id = 307,
                            Force = 820,
                            Name = "Yamada Arinobu"
                        },
                        new
                        {
                            Id = 308,
                            Force = 119,
                            Name = "Yamada Nagamasa"
                        },
                        new
                        {
                            Id = 309,
                            Force = 1689,
                            Name = "Yamagata Masakage"
                        },
                        new
                        {
                            Id = 310,
                            Force = 635,
                            Name = "Yamakawa Hiroshi"
                        },
                        new
                        {
                            Id = 311,
                            Force = 1204,
                            Name = "Yamakawa Kenjirō"
                        },
                        new
                        {
                            Id = 312,
                            Force = 1495,
                            Name = "Yamakawa Naoe"
                        },
                        new
                        {
                            Id = 313,
                            Force = 388,
                            Name = "Yamanaka Yukimori"
                        },
                        new
                        {
                            Id = 314,
                            Force = 1620,
                            Name = "Yamanami Keisuke"
                        },
                        new
                        {
                            Id = 315,
                            Force = 147,
                            Name = "Yamaoka Tesshū"
                        },
                        new
                        {
                            Id = 316,
                            Force = 1685,
                            Name = "Yanagawa Kenzaburo"
                        },
                        new
                        {
                            Id = 317,
                            Force = 1418,
                            Name = "Yanagisawa Yoshiyasu"
                        },
                        new
                        {
                            Id = 318,
                            Force = 274,
                            Name = "Yonekura Shigetsugu"
                        },
                        new
                        {
                            Id = 319,
                            Force = 224,
                            Name = "Yūki Hideyasu"
                        },
                        new
                        {
                            Id = 320,
                            Force = 862,
                            Name = "Yasuke"
                        });
                });

            modelBuilder.Entity("BO.ArtMartialSamourai", b =>
                {
                    b.HasOne("BO.Samourai", null)
                        .WithMany()
                        .HasForeignKey("ArtMartialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BO.ArtMartial", null)
                        .WithMany()
                        .HasForeignKey("SamouraiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BO.Samourai", b =>
                {
                    b.HasOne("BO.Arme", "Arme")
                        .WithMany()
                        .HasForeignKey("ArmeId");

                    b.Navigation("Arme");
                });
#pragma warning restore 612, 618
        }
    }
}
