// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TPDojo;

#nullable disable

namespace TPDojo.Migrations
{
    [DbContext(typeof(DojoDbContext))]
    [Migration("20230822101650_Fixture")]
    partial class Fixture
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BO.Arme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Degat")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Arme");
                });

            modelBuilder.Entity("BO.Samourai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArmeId")
                        .HasColumnType("int");

                    b.Property<int>("Force")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArmeId");

                    b.ToTable("Samourai");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Force = 1876,
                            Name = "Abe Masakatsu"
                        },
                        new
                        {
                            Id = 2,
                            Force = 890,
                            Name = "Adachi Yasumori"
                        },
                        new
                        {
                            Id = 3,
                            Force = 467,
                            Name = "Adachi Kagemori"
                        },
                        new
                        {
                            Id = 4,
                            Force = 1452,
                            Name = "Adams William"
                        },
                        new
                        {
                            Id = 5,
                            Force = 175,
                            Name = "Aiou Mototsuna"
                        },
                        new
                        {
                            Id = 6,
                            Force = 473,
                            Name = "Akai Terukage"
                        },
                        new
                        {
                            Id = 7,
                            Force = 383,
                            Name = "Akao Kiyotsuna"
                        },
                        new
                        {
                            Id = 8,
                            Force = 1041,
                            Name = "Akechi Mitsuhide"
                        },
                        new
                        {
                            Id = 9,
                            Force = 1912,
                            Name = "Akiyama Nobutomo"
                        },
                        new
                        {
                            Id = 10,
                            Force = 736,
                            Name = "Amago Haruhisa"
                        },
                        new
                        {
                            Id = 11,
                            Force = 848,
                            Name = "Amago Yoshihisa"
                        },
                        new
                        {
                            Id = 12,
                            Force = 1861,
                            Name = "Andō Morinari"
                        },
                        new
                        {
                            Id = 13,
                            Force = 1922,
                            Name = "Ankokuji Ekei"
                        },
                        new
                        {
                            Id = 14,
                            Force = 1172,
                            Name = "Aochi Shigetsuna"
                        },
                        new
                        {
                            Id = 15,
                            Force = 220,
                            Name = "Aokage Takaakira"
                        },
                        new
                        {
                            Id = 16,
                            Force = 743,
                            Name = "Aoki Kazushige"
                        },
                        new
                        {
                            Id = 17,
                            Force = 1151,
                            Name = "Akahori Chohichi"
                        },
                        new
                        {
                            Id = 18,
                            Force = 617,
                            Name = "Arai Hakuseki"
                        },
                        new
                        {
                            Id = 19,
                            Force = 592,
                            Name = "Araki Motokiyo"
                        },
                        new
                        {
                            Id = 20,
                            Force = 560,
                            Name = "Araki Murashige"
                        },
                        new
                        {
                            Id = 21,
                            Force = 234,
                            Name = "Araki Muratsugu"
                        },
                        new
                        {
                            Id = 22,
                            Force = 1942,
                            Name = "Arima Kihei"
                        },
                        new
                        {
                            Id = 23,
                            Force = 16,
                            Name = "Asakura Yoshikage"
                        },
                        new
                        {
                            Id = 24,
                            Force = 362,
                            Name = "Ayame Kagekatsu"
                        },
                        new
                        {
                            Id = 25,
                            Force = 1302,
                            Name = "Azai Hisamasa"
                        },
                        new
                        {
                            Id = 26,
                            Force = 144,
                            Name = "Azai Nagamasa"
                        },
                        new
                        {
                            Id = 27,
                            Force = 1902,
                            Name = "Azai Sukemasa"
                        },
                        new
                        {
                            Id = 28,
                            Force = 809,
                            Name = "Baba Nobufusa"
                        },
                        new
                        {
                            Id = 29,
                            Force = 544,
                            Name = "Bessho Nagaharu"
                        },
                        new
                        {
                            Id = 30,
                            Force = 381,
                            Name = "Chacha"
                        },
                        new
                        {
                            Id = 31,
                            Force = 1247,
                            Name = "Chiba Shusaku Narimasa"
                        },
                        new
                        {
                            Id = 32,
                            Force = 416,
                            Name = "Chōsokabe Morichika"
                        },
                        new
                        {
                            Id = 33,
                            Force = 1064,
                            Name = "Chōsokabe Kunichika"
                        },
                        new
                        {
                            Id = 34,
                            Force = 626,
                            Name = "Chōsokabe Motochika"
                        },
                        new
                        {
                            Id = 35,
                            Force = 145,
                            Name = "Chōsokabe Nobuchika"
                        },
                        new
                        {
                            Id = 36,
                            Force = 23,
                            Name = "Collache Eugène"
                        },
                        new
                        {
                            Id = 37,
                            Force = 1076,
                            Name = "Date Masamune"
                        },
                        new
                        {
                            Id = 38,
                            Force = 412,
                            Name = "Date Shigezane"
                        },
                        new
                        {
                            Id = 39,
                            Force = 1523,
                            Name = "Doi Toshikatsu"
                        },
                        new
                        {
                            Id = 40,
                            Force = 1527,
                            Name = "Etō Shinpei"
                        },
                        new
                        {
                            Id = 41,
                            Force = 804,
                            Name = "Endō Naotsune"
                        },
                        new
                        {
                            Id = 42,
                            Force = 2,
                            Name = "Enjoji Nobutane"
                        },
                        new
                        {
                            Id = 43,
                            Force = 1444,
                            Name = "ENameoto Takeaki"
                        },
                        new
                        {
                            Id = 44,
                            Force = 1291,
                            Name = "Era Fusahide"
                        },
                        new
                        {
                            Id = 45,
                            Force = 1012,
                            Name = "Fūma Kotarō"
                        },
                        new
                        {
                            Id = 46,
                            Force = 355,
                            Name = "Fuwa Mitsuharu"
                        },
                        new
                        {
                            Id = 47,
                            Force = 1973,
                            Name = "Fukushima Masanori"
                        },
                        new
                        {
                            Id = 48,
                            Force = 172,
                            Name = "Gamō Katahide"
                        },
                        new
                        {
                            Id = 49,
                            Force = 1001,
                            Name = "Gamō Ujisato"
                        },
                        new
                        {
                            Id = 50,
                            Force = 1573,
                            Name = "Harada Naomasa"
                        },
                        new
                        {
                            Id = 51,
                            Force = 3,
                            Name = "Harada Nobutane"
                        },
                        new
                        {
                            Id = 52,
                            Force = 1916,
                            Name = "Harada Sanosuke"
                        },
                        new
                        {
                            Id = 53,
                            Force = 1126,
                            Name = "Hasekura Tsunenaga"
                        },
                        new
                        {
                            Id = 54,
                            Force = 1808,
                            Name = "Hattori Hanzō"
                        },
                        new
                        {
                            Id = 55,
                            Force = 335,
                            Name = "Hatano Hideharu"
                        },
                        new
                        {
                            Id = 56,
                            Force = 1505,
                            Name = "Hasegawa Eishin"
                        },
                        new
                        {
                            Id = 57,
                            Force = 731,
                            Name = "Hayashizaki Jinsuke Shigenobu"
                        },
                        new
                        {
                            Id = 58,
                            Force = 824,
                            Name = "Hayashi Narinaga"
                        },
                        new
                        {
                            Id = 59,
                            Force = 274,
                            Name = "Hijikata Toshizo"
                        },
                        new
                        {
                            Id = 60,
                            Force = 180,
                            Name = "Hirate Masahide"
                        },
                        new
                        {
                            Id = 61,
                            Force = 602,
                            Name = "Hitotsubashi Keiki"
                        },
                        new
                        {
                            Id = 62,
                            Force = 1232,
                            Name = "Hōjō Masako"
                        },
                        new
                        {
                            Id = 63,
                            Force = 39,
                            Name = "Hōjō Tokimune"
                        },
                        new
                        {
                            Id = 64,
                            Force = 151,
                            Name = "Hōjō Ujiyasu"
                        },
                        new
                        {
                            Id = 65,
                            Force = 1790,
                            Name = "Hōjō Ujimasa"
                        },
                        new
                        {
                            Id = 66,
                            Force = 1580,
                            Name = "Honda Tadakatsu"
                        },
                        new
                        {
                            Id = 67,
                            Force = 990,
                            Name = "Honda Tadatomo"
                        },
                        new
                        {
                            Id = 68,
                            Force = 1079,
                            Name = "Honganji Kennyo"
                        },
                        new
                        {
                            Id = 69,
                            Force = 204,
                            Name = "Horio Yoshiharu"
                        },
                        new
                        {
                            Id = 70,
                            Force = 1869,
                            Name = "Hosokawa Fujitaka"
                        },
                        new
                        {
                            Id = 71,
                            Force = 1929,
                            Name = "Hosokawa Gracia"
                        },
                        new
                        {
                            Id = 72,
                            Force = 316,
                            Name = "Hosokawa Tadaoki"
                        },
                        new
                        {
                            Id = 73,
                            Force = 805,
                            Name = "Hotta Masatoshi"
                        },
                        new
                        {
                            Id = 74,
                            Force = 1547,
                            Name = "Ii Naoaki"
                        },
                        new
                        {
                            Id = 75,
                            Force = 968,
                            Name = "Ii Naomasa"
                        },
                        new
                        {
                            Id = 76,
                            Force = 1426,
                            Name = "Ii Naomori"
                        },
                        new
                        {
                            Id = 77,
                            Force = 32,
                            Name = "Ii Naonaka"
                        },
                        new
                        {
                            Id = 78,
                            Force = 1337,
                            Name = "Ii Naosuke"
                        },
                        new
                        {
                            Id = 79,
                            Force = 743,
                            Name = "Ii Naotaka"
                        },
                        new
                        {
                            Id = 80,
                            Force = 1380,
                            Name = "Ii Naotora"
                        },
                        new
                        {
                            Id = 81,
                            Force = 504,
                            Name = "Ii Naoyuki"
                        },
                        new
                        {
                            Id = 82,
                            Force = 1821,
                            Name = "Ii Naozumi"
                        },
                        new
                        {
                            Id = 83,
                            Force = 533,
                            Name = "Iizasa Ienao"
                        },
                        new
                        {
                            Id = 84,
                            Force = 1378,
                            Name = "Ijuin Tadaaki"
                        },
                        new
                        {
                            Id = 85,
                            Force = 545,
                            Name = "Ikeda Tsuneoki"
                        },
                        new
                        {
                            Id = 86,
                            Force = 1888,
                            Name = "Imagawa Ujizane"
                        },
                        new
                        {
                            Id = 87,
                            Force = 938,
                            Name = "Imagawa Yoshimoto"
                        },
                        new
                        {
                            Id = 88,
                            Force = 1048,
                            Name = "Imai Kanehira"
                        },
                        new
                        {
                            Id = 89,
                            Force = 1170,
                            Name = "Inaba Yoshimichi"
                        },
                        new
                        {
                            Id = 90,
                            Force = 1344,
                            Name = "Inugami Nagayasu"
                        },
                        new
                        {
                            Id = 91,
                            Force = 1029,
                            Name = "Ishida Mitsunari"
                        },
                        new
                        {
                            Id = 92,
                            Force = 1352,
                            Name = "Isshiki Fujinaga"
                        },
                        new
                        {
                            Id = 93,
                            Force = 145,
                            Name = "Itagaki Nobukata"
                        },
                        new
                        {
                            Id = 94,
                            Force = 1712,
                            Name = "Itō Hirobumi"
                        },
                        new
                        {
                            Id = 95,
                            Force = 565,
                            Name = "Iwanari Tomomichi"
                        },
                        new
                        {
                            Id = 96,
                            Force = 877,
                            Name = "Jinbo Nagamoto"
                        },
                        new
                        {
                            Id = 97,
                            Force = 92,
                            Name = "Jonas Tönse"
                        },
                        new
                        {
                            Id = 98,
                            Force = 1711,
                            Name = "Kannan Kumar(Salem)"
                        },
                        new
                        {
                            Id = 99,
                            Force = 445,
                            Name = "Kakeda Toshimune"
                        },
                        new
                        {
                            Id = 100,
                            Force = 408,
                            Name = "Kaneko Ietada"
                        },
                        new
                        {
                            Id = 101,
                            Force = 1235,
                            Name = "Katagiri Katsumoto"
                        },
                        new
                        {
                            Id = 102,
                            Force = 1683,
                            Name = "Katakura Kojūro"
                        },
                        new
                        {
                            Id = 103,
                            Force = 1823,
                            Name = "Katakura Shigenaga"
                        },
                        new
                        {
                            Id = 104,
                            Force = 473,
                            Name = "Kataoka Mitsumasa"
                        },
                        new
                        {
                            Id = 105,
                            Force = 755,
                            Name = "Katō Kiyomasa"
                        },
                        new
                        {
                            Id = 106,
                            Force = 1513,
                            Name = "Kawakami Gensai"
                        },
                        new
                        {
                            Id = 107,
                            Force = 1868,
                            Name = "Kido Takayoshi"
                        },
                        new
                        {
                            Id = 108,
                            Force = 1995,
                            Name = "Kikkawa Hiroie"
                        },
                        new
                        {
                            Id = 109,
                            Force = 1634,
                            Name = "Kimotsuki Kanetsugu"
                        },
                        new
                        {
                            Id = 110,
                            Force = 293,
                            Name = "Kitamura Kansuke"
                        },
                        new
                        {
                            Id = 111,
                            Force = 117,
                            Name = "Kobayakawa Hideaki"
                        },
                        new
                        {
                            Id = 112,
                            Force = 1922,
                            Name = "Kobayakawa Hidekane"
                        },
                        new
                        {
                            Id = 113,
                            Force = 1848,
                            Name = "Kobayakawa Takakage"
                        },
                        new
                        {
                            Id = 114,
                            Force = 1208,
                            Name = "Konishi Yukinaga"
                        },
                        new
                        {
                            Id = 115,
                            Force = 1769,
                            Name = "Kojima Toyoharu"
                        },
                        new
                        {
                            Id = 116,
                            Force = 743,
                            Name = "Kuroda Kanbei"
                        },
                        new
                        {
                            Id = 117,
                            Force = 235,
                            Name = "Kuroda Kiyotaka"
                        },
                        new
                        {
                            Id = 118,
                            Force = 775,
                            Name = "Kusunoki Masashige"
                        },
                        new
                        {
                            Id = 119,
                            Force = 1761,
                            Name = "Kuwana Tarozaemon"
                        },
                        new
                        {
                            Id = 120,
                            Force = 286,
                            Name = "Kumagai Naozane"
                        },
                        new
                        {
                            Id = 121,
                            Force = 1050,
                            Name = "Maeda Keiji"
                        },
                        new
                        {
                            Id = 122,
                            Force = 65,
                            Name = "Maeda Matsu"
                        },
                        new
                        {
                            Id = 123,
                            Force = 732,
                            Name = "Maeda Nagatane"
                        },
                        new
                        {
                            Id = 124,
                            Force = 668,
                            Name = "Maeda Toshiie"
                        },
                        new
                        {
                            Id = 125,
                            Force = 802,
                            Name = "Maeda Toshinaga"
                        },
                        new
                        {
                            Id = 126,
                            Force = 558,
                            Name = "Maeda Toshitsune"
                        },
                        new
                        {
                            Id = 127,
                            Force = 349,
                            Name = "Magome Kageyu"
                        },
                        new
                        {
                            Id = 128,
                            Force = 408,
                            Name = "Manabe Akifusa"
                        },
                        new
                        {
                            Id = 129,
                            Force = 733,
                            Name = "Matsudaira Katamori"
                        },
                        new
                        {
                            Id = 130,
                            Force = 1236,
                            Name = "Matsudaira Nobutsuna"
                        },
                        new
                        {
                            Id = 131,
                            Force = 988,
                            Name = "Matsudaira Nobuyasu"
                        },
                        new
                        {
                            Id = 132,
                            Force = 675,
                            Name = "Matsudaira Higo no Kami Katamori"
                        },
                        new
                        {
                            Id = 133,
                            Force = 438,
                            Name = "Matsudaira Sadanobu"
                        },
                        new
                        {
                            Id = 134,
                            Force = 991,
                            Name = "Matsudaira Tadayoshi"
                        },
                        new
                        {
                            Id = 135,
                            Force = 8,
                            Name = "Matsudaira Teru"
                        },
                        new
                        {
                            Id = 136,
                            Force = 104,
                            Name = "Matsunaga Hisahide"
                        },
                        new
                        {
                            Id = 137,
                            Force = 97,
                            Name = "Matsunaga Hisamichi"
                        },
                        new
                        {
                            Id = 138,
                            Force = 150,
                            Name = "Matsuo Bashō"
                        },
                        new
                        {
                            Id = 139,
                            Force = 965,
                            Name = "Matsudaira Motoyasu"
                        },
                        new
                        {
                            Id = 140,
                            Force = 660,
                            Name = "Minamoto no Mitsunaka"
                        },
                        new
                        {
                            Id = 141,
                            Force = 691,
                            Name = "Minamoto no Yoshiie"
                        },
                        new
                        {
                            Id = 142,
                            Force = 917,
                            Name = "Minamoto no Yoshimitsu"
                        },
                        new
                        {
                            Id = 143,
                            Force = 1951,
                            Name = "Minamoto no Yoshinaka"
                        },
                        new
                        {
                            Id = 144,
                            Force = 1812,
                            Name = "Minamoto no Yoshitomo"
                        },
                        new
                        {
                            Id = 145,
                            Force = 1296,
                            Name = "Minamoto no Yoshitsune"
                        },
                        new
                        {
                            Id = 146,
                            Force = 580,
                            Name = "Minamoto no Tameyoshi"
                        },
                        new
                        {
                            Id = 147,
                            Force = 1061,
                            Name = "Minamoto no Yorimasa"
                        },
                        new
                        {
                            Id = 148,
                            Force = 1616,
                            Name = "Minamoto no Yorimitsu"
                        },
                        new
                        {
                            Id = 149,
                            Force = 531,
                            Name = "Minamoto no Yoritomo"
                        },
                        new
                        {
                            Id = 150,
                            Force = 465,
                            Name = "Minamoto no Noriyori"
                        },
                        new
                        {
                            Id = 151,
                            Force = 1569,
                            Name = "Minoro Takashi"
                        },
                        new
                        {
                            Id = 152,
                            Force = 484,
                            Name = "Miura Anjin"
                        },
                        new
                        {
                            Id = 153,
                            Force = 1943,
                            Name = "Miura Yoshimoto"
                        },
                        new
                        {
                            Id = 154,
                            Force = 310,
                            Name = "Miyamoto Musashi"
                        },
                        new
                        {
                            Id = 155,
                            Force = 831,
                            Name = "Miyoshi Chōkei"
                        },
                        new
                        {
                            Id = 156,
                            Force = 1756,
                            Name = "Miyoshi Kazuhide"
                        },
                        new
                        {
                            Id = 157,
                            Force = 222,
                            Name = "Miyoshi Masaga"
                        },
                        new
                        {
                            Id = 158,
                            Force = 1485,
                            Name = "Miyoshi Masayasu"
                        },
                        new
                        {
                            Id = 159,
                            Force = 663,
                            Name = "Miyoshi Moriyata"
                        },
                        new
                        {
                            Id = 160,
                            Force = 674,
                            Name = "Miyoshi Nagayuki"
                        },
                        new
                        {
                            Id = 161,
                            Force = 1523,
                            Name = "Miyoshi Yoshitsugu"
                        },
                        new
                        {
                            Id = 162,
                            Force = 993,
                            Name = "Mizuno Tadakuni"
                        },
                        new
                        {
                            Id = 163,
                            Force = 1373,
                            Name = "Moniwa Yoshinao"
                        },
                        new
                        {
                            Id = 164,
                            Force = 509,
                            Name = "Mōri Motonari"
                        },
                        new
                        {
                            Id = 165,
                            Force = 1389,
                            Name = "Mōri Nagasada"
                        },
                        new
                        {
                            Id = 166,
                            Force = 391,
                            Name = "Mori Nagayoshi"
                        },
                        new
                        {
                            Id = 167,
                            Force = 1377,
                            Name = "Mōri Okimoto"
                        },
                        new
                        {
                            Id = 168,
                            Force = 1205,
                            Name = "Mori Ranmaru"
                        },
                        new
                        {
                            Id = 169,
                            Force = 904,
                            Name = "Mōri Takamoto"
                        },
                        new
                        {
                            Id = 170,
                            Force = 306,
                            Name = "Mori Tadamasa"
                        },
                        new
                        {
                            Id = 171,
                            Force = 677,
                            Name = "Mōri Terumoto"
                        },
                        new
                        {
                            Id = 172,
                            Force = 306,
                            Name = "Mori Yoshinari"
                        },
                        new
                        {
                            Id = 173,
                            Force = 708,
                            Name = "Murai Sadakatsu"
                        },
                        new
                        {
                            Id = 174,
                            Force = 220,
                            Name = "Nagakura Shinpachi"
                        },
                        new
                        {
                            Id = 175,
                            Force = 840,
                            Name = "Nagao Harukage"
                        },
                        new
                        {
                            Id = 176,
                            Force = 1937,
                            Name = "Nagao Kagenobu"
                        },
                        new
                        {
                            Id = 177,
                            Force = 1314,
                            Name = "Nagao Masakage"
                        },
                        new
                        {
                            Id = 178,
                            Force = 1541,
                            Name = "Nagao Tamekage"
                        },
                        new
                        {
                            Id = 179,
                            Force = 754,
                            Name = "Nakagawa Kiyohide"
                        },
                        new
                        {
                            Id = 180,
                            Force = 1046,
                            Name = "Nakaoka Shintarō"
                        },
                        new
                        {
                            Id = 181,
                            Force = 1028,
                            Name = "Naoe Kagetsuna"
                        },
                        new
                        {
                            Id = 182,
                            Force = 1317,
                            Name = "Naoe Kanetsugu"
                        },
                        new
                        {
                            Id = 183,
                            Force = 78,
                            Name = "Narita Kaihime"
                        },
                        new
                        {
                            Id = 184,
                            Force = 938,
                            Name = "Nene"
                        },
                        new
                        {
                            Id = 185,
                            Force = 480,
                            Name = "Nihonmatsu Yoshitsugu"
                        },
                        new
                        {
                            Id = 186,
                            Force = 1242,
                            Name = "Niimi Nishiki"
                        },
                        new
                        {
                            Id = 187,
                            Force = 1634,
                            Name = "Niiro Tadamoto"
                        },
                        new
                        {
                            Id = 188,
                            Force = 447,
                            Name = "Niwa Nagahide"
                        },
                        new
                        {
                            Id = 189,
                            Force = 301,
                            Name = "Niwa Nagashige"
                        },
                        new
                        {
                            Id = 190,
                            Force = 351,
                            Name = "Oda Hiroyoshi"
                        },
                        new
                        {
                            Id = 191,
                            Force = 502,
                            Name = "Oda Nobuhide"
                        },
                        new
                        {
                            Id = 192,
                            Force = 862,
                            Name = "Oda Nobukata"
                        },
                        new
                        {
                            Id = 193,
                            Force = 583,
                            Name = "Oda Nobukiyo"
                        },
                        new
                        {
                            Id = 194,
                            Force = 1516,
                            Name = "Oda Nobunaga"
                        },
                        new
                        {
                            Id = 195,
                            Force = 239,
                            Name = "Oda Nobutada"
                        },
                        new
                        {
                            Id = 196,
                            Force = 989,
                            Name = "Oda Nobutomo"
                        },
                        new
                        {
                            Id = 197,
                            Force = 1350,
                            Name = "Oda Nobukatsu"
                        },
                        new
                        {
                            Id = 198,
                            Force = 298,
                            Name = "Oda Nobuyasu"
                        },
                        new
                        {
                            Id = 199,
                            Force = 1789,
                            Name = "Ogasawara Shōsai"
                        },
                        new
                        {
                            Id = 200,
                            Force = 293,
                            Name = "Ōishi Kuranosuke"
                        },
                        new
                        {
                            Id = 201,
                            Force = 890,
                            Name = "Okada Izō"
                        },
                        new
                        {
                            Id = 202,
                            Force = 1179,
                            Name = "Judge Ooka"
                        },
                        new
                        {
                            Id = 203,
                            Force = 1681,
                            Name = "Ōta Dōkan"
                        },
                        new
                        {
                            Id = 204,
                            Force = 1822,
                            Name = "Ōtani Yoshitsugu"
                        },
                        new
                        {
                            Id = 205,
                            Force = 715,
                            Name = "Ōtani Yoshiharu"
                        },
                        new
                        {
                            Id = 206,
                            Force = 393,
                            Name = "Ōtomo Sōrin"
                        },
                        new
                        {
                            Id = 207,
                            Force = 974,
                            Name = "Okita Sōji"
                        },
                        new
                        {
                            Id = 208,
                            Force = 675,
                            Name = "Ōkubo Toshimichi"
                        },
                        new
                        {
                            Id = 209,
                            Force = 1259,
                            Name = "OkuNameiya Masaie"
                        },
                        new
                        {
                            Id = 210,
                            Force = 1575,
                            Name = "Ōuchi Yoshitaka"
                        },
                        new
                        {
                            Id = 211,
                            Force = 1783,
                            Name = "Omy Yoshika"
                        },
                        new
                        {
                            Id = 212,
                            Force = 915,
                            Name = "Pore Sufi"
                        },
                        new
                        {
                            Id = 213,
                            Force = 1167,
                            Name = "Reizei Takatoyo"
                        },
                        new
                        {
                            Id = 214,
                            Force = 1416,
                            Name = "Rokkaku Sadayori"
                        },
                        new
                        {
                            Id = 215,
                            Force = 585,
                            Name = "Rokkaku Yoshiharu"
                        },
                        new
                        {
                            Id = 216,
                            Force = 1464,
                            Name = "Rokkaku Yoshikata"
                        },
                        new
                        {
                            Id = 217,
                            Force = 1550,
                            Name = "Rusu Masakage"
                        },
                        new
                        {
                            Id = 218,
                            Force = 1500,
                            Name = "Ryūzōji Takanobu"
                        },
                        new
                        {
                            Id = 219,
                            Force = 554,
                            Name = "Saigo Kiyokazu"
                        },
                        new
                        {
                            Id = 220,
                            Force = 327,
                            Name = "Saigō Masako"
                        },
                        new
                        {
                            Id = 221,
                            Force = 108,
                            Name = "Sagara Taketō"
                        },
                        new
                        {
                            Id = 222,
                            Force = 842,
                            Name = "Saigō Takamori"
                        },
                        new
                        {
                            Id = 223,
                            Force = 1158,
                            Name = "Saigo Yoshikatsu"
                        },
                        new
                        {
                            Id = 224,
                            Force = 944,
                            Name = "Saitō Dōsan"
                        },
                        new
                        {
                            Id = 225,
                            Force = 811,
                            Name = "Saitō Hajime"
                        },
                        new
                        {
                            Id = 226,
                            Force = 5,
                            Name = "Saito Musashibō Benkei"
                        },
                        new
                        {
                            Id = 227,
                            Force = 1928,
                            Name = "Saitō Yoshitatsu"
                        },
                        new
                        {
                            Id = 228,
                            Force = 854,
                            Name = "Sakai Tadakiyo"
                        },
                        new
                        {
                            Id = 229,
                            Force = 1392,
                            Name = "Sakai Tadashige"
                        },
                        new
                        {
                            Id = 230,
                            Force = 1447,
                            Name = "Sakai Tadatsugu"
                        },
                        new
                        {
                            Id = 231,
                            Force = 633,
                            Name = "Sakai Tadayo"
                        },
                        new
                        {
                            Id = 232,
                            Force = 401,
                            Name = "Sakakibara Yasumasa"
                        },
                        new
                        {
                            Id = 233,
                            Force = 1290,
                            Name = "Sakamoto Ryōma"
                        },
                        new
                        {
                            Id = 234,
                            Force = 1775,
                            Name = "Sakuma Morimasa"
                        },
                        new
                        {
                            Id = 235,
                            Force = 1939,
                            Name = "Sakuma Nobumori"
                        },
                        new
                        {
                            Id = 236,
                            Force = 569,
                            Name = "Sanada Akihime"
                        },
                        new
                        {
                            Id = 237,
                            Force = 866,
                            Name = "Sanada Komatsuhime"
                        },
                        new
                        {
                            Id = 238,
                            Force = 41,
                            Name = "Sanada Masayuki"
                        },
                        new
                        {
                            Id = 239,
                            Force = 1284,
                            Name = "Sanada Nobuyuki"
                        },
                        new
                        {
                            Id = 240,
                            Force = 276,
                            Name = "Sanada Yukimura"
                        },
                        new
                        {
                            Id = 241,
                            Force = 33,
                            Name = "Sasaki Kojirō"
                        },
                        new
                        {
                            Id = 242,
                            Force = 963,
                            Name = "Sassa Narimasa"
                        },
                        new
                        {
                            Id = 243,
                            Force = 1079,
                            Name = "Sasuke Sarutobi"
                        },
                        new
                        {
                            Id = 244,
                            Force = 1904,
                            Name = "Serizawa Kamo"
                        },
                        new
                        {
                            Id = 245,
                            Force = 189,
                            Name = "Shibata Katsuie"
                        },
                        new
                        {
                            Id = 246,
                            Force = 313,
                            Name = "Shima Sakon"
                        },
                        new
                        {
                            Id = 247,
                            Force = 748,
                            Name = "Shimada Ichirō"
                        },
                        new
                        {
                            Id = 248,
                            Force = 723,
                            Name = "Shimazu Katsuhisa"
                        },
                        new
                        {
                            Id = 249,
                            Force = 1107,
                            Name = "Shimazu Tadahisa"
                        },
                        new
                        {
                            Id = 250,
                            Force = 676,
                            Name = "Shimazu Tadatsune"
                        },
                        new
                        {
                            Id = 251,
                            Force = 39,
                            Name = "Shimazu Tadayoshi"
                        },
                        new
                        {
                            Id = 252,
                            Force = 1106,
                            Name = "Shimazu Takahisa"
                        },
                        new
                        {
                            Id = 253,
                            Force = 1863,
                            Name = "Shimazu Toyohisa"
                        },
                        new
                        {
                            Id = 254,
                            Force = 1138,
                            Name = "Shimazu Yoshihiro"
                        },
                        new
                        {
                            Id = 255,
                            Force = 1736,
                            Name = "Shimazu Yoshihisa"
                        },
                        new
                        {
                            Id = 256,
                            Force = 125,
                            Name = "Shindou Hiroshii"
                        },
                        new
                        {
                            Id = 257,
                            Force = 55,
                            Name = "Sogo Nagayasu"
                        },
                        new
                        {
                            Id = 258,
                            Force = 310,
                            Name = "Sue Yoshitaka"
                        },
                        new
                        {
                            Id = 259,
                            Force = 1591,
                            Name = "Tachibana Muneshige"
                        },
                        new
                        {
                            Id = 260,
                            Force = 1252,
                            Name = "Tachibana Dōsetsu"
                        },
                        new
                        {
                            Id = 261,
                            Force = 1499,
                            Name = "Tachibana Ginchiyo"
                        },
                        new
                        {
                            Id = 262,
                            Force = 1825,
                            Name = "Taigen Sessai"
                        },
                        new
                        {
                            Id = 263,
                            Force = 848,
                            Name = "Taira no Kiyomori"
                        },
                        new
                        {
                            Id = 264,
                            Force = 1386,
                            Name = "Taira Masakado"
                        },
                        new
                        {
                            Id = 265,
                            Force = 1272,
                            Name = "Takahashi Shigetane"
                        },
                        new
                        {
                            Id = 266,
                            Force = 1206,
                            Name = "Takenaka Shigeharu"
                        },
                        new
                        {
                            Id = 267,
                            Force = 201,
                            Name = "Takasugi Shinsaku"
                        },
                        new
                        {
                            Id = 268,
                            Force = 1313,
                            Name = "Takayama Justo"
                        },
                        new
                        {
                            Id = 269,
                            Force = 124,
                            Name = "Takayama Ukon"
                        },
                        new
                        {
                            Id = 270,
                            Force = 1076,
                            Name = "Takechi Hanpeita"
                        },
                        new
                        {
                            Id = 271,
                            Force = 417,
                            Name = "Takeda Katsuyori"
                        },
                        new
                        {
                            Id = 272,
                            Force = 418,
                            Name = "Takeda Nobukatsu"
                        },
                        new
                        {
                            Id = 273,
                            Force = 1820,
                            Name = "Takeda Nobushige"
                        },
                        new
                        {
                            Id = 274,
                            Force = 1226,
                            Name = "Takeda Shingen"
                        },
                        new
                        {
                            Id = 275,
                            Force = 1845,
                            Name = "Takenaka Hanbei"
                        },
                        new
                        {
                            Id = 276,
                            Force = 1294,
                            Name = "Tani Tadasumi"
                        },
                        new
                        {
                            Id = 277,
                            Force = 1176,
                            Name = "Tōdō Takatora"
                        },
                        new
                        {
                            Id = 278,
                            Force = 1614,
                            Name = "Toki Yorinari"
                        },
                        new
                        {
                            Id = 279,
                            Force = 1453,
                            Name = "Tochimitsu Gantyoki"
                        },
                        new
                        {
                            Id = 280,
                            Force = 701,
                            Name = "Tokugawa Ieyasu"
                        },
                        new
                        {
                            Id = 281,
                            Force = 1031,
                            Name = "Tokugawa Hidetada"
                        },
                        new
                        {
                            Id = 282,
                            Force = 589,
                            Name = "Tokugawa Nariaki"
                        },
                        new
                        {
                            Id = 283,
                            Force = 1851,
                            Name = "Tokugawa Yoshinobu"
                        },
                        new
                        {
                            Id = 284,
                            Force = 1205,
                            Name = "Torii Mototada"
                        },
                        new
                        {
                            Id = 285,
                            Force = 705,
                            Name = "Toyotomi Hidenaga"
                        },
                        new
                        {
                            Id = 286,
                            Force = 1524,
                            Name = "Toyotomi Hideyoshi"
                        },
                        new
                        {
                            Id = 287,
                            Force = 1612,
                            Name = "Toyotomi Hideyori"
                        },
                        new
                        {
                            Id = 288,
                            Force = 1476,
                            Name = "Tozuka Tadaharu"
                        },
                        new
                        {
                            Id = 289,
                            Force = 1654,
                            Name = "Tsukahara Bokuden"
                        },
                        new
                        {
                            Id = 290,
                            Force = 0,
                            Name = "Uesugi Kagekatsu"
                        },
                        new
                        {
                            Id = 291,
                            Force = 73,
                            Name = "Uesugi Kagetora"
                        },
                        new
                        {
                            Id = 292,
                            Force = 1500,
                            Name = "Uesugi Kenshin"
                        },
                        new
                        {
                            Id = 293,
                            Force = 1041,
                            Name = "Ujiie Naotomo"
                        },
                        new
                        {
                            Id = 294,
                            Force = 1775,
                            Name = "Ukita Naoie"
                        },
                        new
                        {
                            Id = 295,
                            Force = 1638,
                            Name = "Ukita Okiie"
                        },
                        new
                        {
                            Id = 296,
                            Force = 463,
                            Name = "Umezawa Michiharu"
                        },
                        new
                        {
                            Id = 297,
                            Force = 989,
                            Name = "Usami Sadamitsu"
                        },
                        new
                        {
                            Id = 298,
                            Force = 1625,
                            Name = "Uyama Hisanobu"
                        },
                        new
                        {
                            Id = 299,
                            Force = 1371,
                            Name = "Wada Shinsuke"
                        },
                        new
                        {
                            Id = 300,
                            Force = 1079,
                            Name = "Watanabe Kazan"
                        },
                        new
                        {
                            Id = 301,
                            Force = 1622,
                            Name = "Watanabe no Tsuna"
                        },
                        new
                        {
                            Id = 302,
                            Force = 1116,
                            Name = "Yasumero Kenshin"
                        },
                        new
                        {
                            Id = 303,
                            Force = 1559,
                            Name = "Yagyū Jūbei Mitsuyoshi"
                        },
                        new
                        {
                            Id = 304,
                            Force = 807,
                            Name = "Yagyū Munenori"
                        },
                        new
                        {
                            Id = 305,
                            Force = 600,
                            Name = "Yamauchi Kazutoyo"
                        },
                        new
                        {
                            Id = 306,
                            Force = 1879,
                            Name = "Yamada Arinaga"
                        },
                        new
                        {
                            Id = 307,
                            Force = 403,
                            Name = "Yamada Arinobu"
                        },
                        new
                        {
                            Id = 308,
                            Force = 326,
                            Name = "Yamada Nagamasa"
                        },
                        new
                        {
                            Id = 309,
                            Force = 1565,
                            Name = "Yamagata Masakage"
                        },
                        new
                        {
                            Id = 310,
                            Force = 1475,
                            Name = "Yamakawa Hiroshi"
                        },
                        new
                        {
                            Id = 311,
                            Force = 1930,
                            Name = "Yamakawa Kenjirō"
                        },
                        new
                        {
                            Id = 312,
                            Force = 999,
                            Name = "Yamakawa Naoe"
                        },
                        new
                        {
                            Id = 313,
                            Force = 1882,
                            Name = "Yamanaka Yukimori"
                        },
                        new
                        {
                            Id = 314,
                            Force = 371,
                            Name = "Yamanami Keisuke"
                        },
                        new
                        {
                            Id = 315,
                            Force = 1668,
                            Name = "Yamaoka Tesshū"
                        },
                        new
                        {
                            Id = 316,
                            Force = 1225,
                            Name = "Yanagawa Kenzaburo"
                        },
                        new
                        {
                            Id = 317,
                            Force = 1235,
                            Name = "Yanagisawa Yoshiyasu"
                        },
                        new
                        {
                            Id = 318,
                            Force = 37,
                            Name = "Yonekura Shigetsugu"
                        },
                        new
                        {
                            Id = 319,
                            Force = 71,
                            Name = "Yūki Hideyasu"
                        },
                        new
                        {
                            Id = 320,
                            Force = 807,
                            Name = "Yasuke"
                        });
                });

            modelBuilder.Entity("BO.Samourai", b =>
                {
                    b.HasOne("BO.Arme", "Arme")
                        .WithMany()
                        .HasForeignKey("ArmeId");

                    b.Navigation("Arme");
                });
#pragma warning restore 612, 618
        }
    }
}
