// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TPDojo;

#nullable disable

namespace TPDojo.Migrations
{
    [DbContext(typeof(DojoDbContext))]
    [Migration("20230823082257_ArtMartialSamourai")]
    partial class ArtMartialSamourai
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArtMartialSamourai", b =>
                {
                    b.Property<int>("ArtMartialsId")
                        .HasColumnType("int");

                    b.Property<int>("SamouraisId")
                        .HasColumnType("int");

                    b.HasKey("ArtMartialsId", "SamouraisId");

                    b.HasIndex("SamouraisId");

                    b.ToTable("ArtMartialSamourai");
                });

            modelBuilder.Entity("BO.Arme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Degat")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Arme");
                });

            modelBuilder.Entity("BO.ArtMartial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ArtMartial");
                });

            modelBuilder.Entity("BO.Samourai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArmeId")
                        .HasColumnType("int");

                    b.Property<int>("Force")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArmeId");

                    b.ToTable("Samourai");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Force = 1703,
                            Name = "Abe Masakatsu"
                        },
                        new
                        {
                            Id = 2,
                            Force = 1373,
                            Name = "Adachi Yasumori"
                        },
                        new
                        {
                            Id = 3,
                            Force = 282,
                            Name = "Adachi Kagemori"
                        },
                        new
                        {
                            Id = 4,
                            Force = 976,
                            Name = "Adams William"
                        },
                        new
                        {
                            Id = 5,
                            Force = 895,
                            Name = "Aiou Mototsuna"
                        },
                        new
                        {
                            Id = 6,
                            Force = 1835,
                            Name = "Akai Terukage"
                        },
                        new
                        {
                            Id = 7,
                            Force = 747,
                            Name = "Akao Kiyotsuna"
                        },
                        new
                        {
                            Id = 8,
                            Force = 1430,
                            Name = "Akechi Mitsuhide"
                        },
                        new
                        {
                            Id = 9,
                            Force = 406,
                            Name = "Akiyama Nobutomo"
                        },
                        new
                        {
                            Id = 10,
                            Force = 740,
                            Name = "Amago Haruhisa"
                        },
                        new
                        {
                            Id = 11,
                            Force = 188,
                            Name = "Amago Yoshihisa"
                        },
                        new
                        {
                            Id = 12,
                            Force = 1874,
                            Name = "Andō Morinari"
                        },
                        new
                        {
                            Id = 13,
                            Force = 1726,
                            Name = "Ankokuji Ekei"
                        },
                        new
                        {
                            Id = 14,
                            Force = 1203,
                            Name = "Aochi Shigetsuna"
                        },
                        new
                        {
                            Id = 15,
                            Force = 209,
                            Name = "Aokage Takaakira"
                        },
                        new
                        {
                            Id = 16,
                            Force = 1918,
                            Name = "Aoki Kazushige"
                        },
                        new
                        {
                            Id = 17,
                            Force = 1413,
                            Name = "Akahori Chohichi"
                        },
                        new
                        {
                            Id = 18,
                            Force = 564,
                            Name = "Arai Hakuseki"
                        },
                        new
                        {
                            Id = 19,
                            Force = 207,
                            Name = "Araki Motokiyo"
                        },
                        new
                        {
                            Id = 20,
                            Force = 884,
                            Name = "Araki Murashige"
                        },
                        new
                        {
                            Id = 21,
                            Force = 436,
                            Name = "Araki Muratsugu"
                        },
                        new
                        {
                            Id = 22,
                            Force = 10,
                            Name = "Arima Kihei"
                        },
                        new
                        {
                            Id = 23,
                            Force = 1588,
                            Name = "Asakura Yoshikage"
                        },
                        new
                        {
                            Id = 24,
                            Force = 51,
                            Name = "Ayame Kagekatsu"
                        },
                        new
                        {
                            Id = 25,
                            Force = 886,
                            Name = "Azai Hisamasa"
                        },
                        new
                        {
                            Id = 26,
                            Force = 926,
                            Name = "Azai Nagamasa"
                        },
                        new
                        {
                            Id = 27,
                            Force = 1639,
                            Name = "Azai Sukemasa"
                        },
                        new
                        {
                            Id = 28,
                            Force = 1003,
                            Name = "Baba Nobufusa"
                        },
                        new
                        {
                            Id = 29,
                            Force = 195,
                            Name = "Bessho Nagaharu"
                        },
                        new
                        {
                            Id = 30,
                            Force = 1386,
                            Name = "Chacha"
                        },
                        new
                        {
                            Id = 31,
                            Force = 614,
                            Name = "Chiba Shusaku Narimasa"
                        },
                        new
                        {
                            Id = 32,
                            Force = 1780,
                            Name = "Chōsokabe Morichika"
                        },
                        new
                        {
                            Id = 33,
                            Force = 36,
                            Name = "Chōsokabe Kunichika"
                        },
                        new
                        {
                            Id = 34,
                            Force = 1698,
                            Name = "Chōsokabe Motochika"
                        },
                        new
                        {
                            Id = 35,
                            Force = 1956,
                            Name = "Chōsokabe Nobuchika"
                        },
                        new
                        {
                            Id = 36,
                            Force = 637,
                            Name = "Collache Eugène"
                        },
                        new
                        {
                            Id = 37,
                            Force = 1823,
                            Name = "Date Masamune"
                        },
                        new
                        {
                            Id = 38,
                            Force = 1851,
                            Name = "Date Shigezane"
                        },
                        new
                        {
                            Id = 39,
                            Force = 823,
                            Name = "Doi Toshikatsu"
                        },
                        new
                        {
                            Id = 40,
                            Force = 848,
                            Name = "Etō Shinpei"
                        },
                        new
                        {
                            Id = 41,
                            Force = 1165,
                            Name = "Endō Naotsune"
                        },
                        new
                        {
                            Id = 42,
                            Force = 1404,
                            Name = "Enjoji Nobutane"
                        },
                        new
                        {
                            Id = 43,
                            Force = 1885,
                            Name = "ENameoto Takeaki"
                        },
                        new
                        {
                            Id = 44,
                            Force = 484,
                            Name = "Era Fusahide"
                        },
                        new
                        {
                            Id = 45,
                            Force = 891,
                            Name = "Fūma Kotarō"
                        },
                        new
                        {
                            Id = 46,
                            Force = 9,
                            Name = "Fuwa Mitsuharu"
                        },
                        new
                        {
                            Id = 47,
                            Force = 213,
                            Name = "Fukushima Masanori"
                        },
                        new
                        {
                            Id = 48,
                            Force = 1957,
                            Name = "Gamō Katahide"
                        },
                        new
                        {
                            Id = 49,
                            Force = 1261,
                            Name = "Gamō Ujisato"
                        },
                        new
                        {
                            Id = 50,
                            Force = 1541,
                            Name = "Harada Naomasa"
                        },
                        new
                        {
                            Id = 51,
                            Force = 1785,
                            Name = "Harada Nobutane"
                        },
                        new
                        {
                            Id = 52,
                            Force = 1905,
                            Name = "Harada Sanosuke"
                        },
                        new
                        {
                            Id = 53,
                            Force = 1381,
                            Name = "Hasekura Tsunenaga"
                        },
                        new
                        {
                            Id = 54,
                            Force = 1442,
                            Name = "Hattori Hanzō"
                        },
                        new
                        {
                            Id = 55,
                            Force = 92,
                            Name = "Hatano Hideharu"
                        },
                        new
                        {
                            Id = 56,
                            Force = 1519,
                            Name = "Hasegawa Eishin"
                        },
                        new
                        {
                            Id = 57,
                            Force = 1236,
                            Name = "Hayashizaki Jinsuke Shigenobu"
                        },
                        new
                        {
                            Id = 58,
                            Force = 1480,
                            Name = "Hayashi Narinaga"
                        },
                        new
                        {
                            Id = 59,
                            Force = 805,
                            Name = "Hijikata Toshizo"
                        },
                        new
                        {
                            Id = 60,
                            Force = 1651,
                            Name = "Hirate Masahide"
                        },
                        new
                        {
                            Id = 61,
                            Force = 772,
                            Name = "Hitotsubashi Keiki"
                        },
                        new
                        {
                            Id = 62,
                            Force = 1114,
                            Name = "Hōjō Masako"
                        },
                        new
                        {
                            Id = 63,
                            Force = 1147,
                            Name = "Hōjō Tokimune"
                        },
                        new
                        {
                            Id = 64,
                            Force = 881,
                            Name = "Hōjō Ujiyasu"
                        },
                        new
                        {
                            Id = 65,
                            Force = 24,
                            Name = "Hōjō Ujimasa"
                        },
                        new
                        {
                            Id = 66,
                            Force = 626,
                            Name = "Honda Tadakatsu"
                        },
                        new
                        {
                            Id = 67,
                            Force = 1040,
                            Name = "Honda Tadatomo"
                        },
                        new
                        {
                            Id = 68,
                            Force = 323,
                            Name = "Honganji Kennyo"
                        },
                        new
                        {
                            Id = 69,
                            Force = 1561,
                            Name = "Horio Yoshiharu"
                        },
                        new
                        {
                            Id = 70,
                            Force = 1581,
                            Name = "Hosokawa Fujitaka"
                        },
                        new
                        {
                            Id = 71,
                            Force = 1275,
                            Name = "Hosokawa Gracia"
                        },
                        new
                        {
                            Id = 72,
                            Force = 1372,
                            Name = "Hosokawa Tadaoki"
                        },
                        new
                        {
                            Id = 73,
                            Force = 1139,
                            Name = "Hotta Masatoshi"
                        },
                        new
                        {
                            Id = 74,
                            Force = 1900,
                            Name = "Ii Naoaki"
                        },
                        new
                        {
                            Id = 75,
                            Force = 613,
                            Name = "Ii Naomasa"
                        },
                        new
                        {
                            Id = 76,
                            Force = 1535,
                            Name = "Ii Naomori"
                        },
                        new
                        {
                            Id = 77,
                            Force = 426,
                            Name = "Ii Naonaka"
                        },
                        new
                        {
                            Id = 78,
                            Force = 215,
                            Name = "Ii Naosuke"
                        },
                        new
                        {
                            Id = 79,
                            Force = 1266,
                            Name = "Ii Naotaka"
                        },
                        new
                        {
                            Id = 80,
                            Force = 957,
                            Name = "Ii Naotora"
                        },
                        new
                        {
                            Id = 81,
                            Force = 1543,
                            Name = "Ii Naoyuki"
                        },
                        new
                        {
                            Id = 82,
                            Force = 1340,
                            Name = "Ii Naozumi"
                        },
                        new
                        {
                            Id = 83,
                            Force = 1439,
                            Name = "Iizasa Ienao"
                        },
                        new
                        {
                            Id = 84,
                            Force = 654,
                            Name = "Ijuin Tadaaki"
                        },
                        new
                        {
                            Id = 85,
                            Force = 797,
                            Name = "Ikeda Tsuneoki"
                        },
                        new
                        {
                            Id = 86,
                            Force = 869,
                            Name = "Imagawa Ujizane"
                        },
                        new
                        {
                            Id = 87,
                            Force = 1914,
                            Name = "Imagawa Yoshimoto"
                        },
                        new
                        {
                            Id = 88,
                            Force = 122,
                            Name = "Imai Kanehira"
                        },
                        new
                        {
                            Id = 89,
                            Force = 36,
                            Name = "Inaba Yoshimichi"
                        },
                        new
                        {
                            Id = 90,
                            Force = 1406,
                            Name = "Inugami Nagayasu"
                        },
                        new
                        {
                            Id = 91,
                            Force = 1409,
                            Name = "Ishida Mitsunari"
                        },
                        new
                        {
                            Id = 92,
                            Force = 700,
                            Name = "Isshiki Fujinaga"
                        },
                        new
                        {
                            Id = 93,
                            Force = 639,
                            Name = "Itagaki Nobukata"
                        },
                        new
                        {
                            Id = 94,
                            Force = 1258,
                            Name = "Itō Hirobumi"
                        },
                        new
                        {
                            Id = 95,
                            Force = 1856,
                            Name = "Iwanari Tomomichi"
                        },
                        new
                        {
                            Id = 96,
                            Force = 1903,
                            Name = "Jinbo Nagamoto"
                        },
                        new
                        {
                            Id = 97,
                            Force = 916,
                            Name = "Jonas Tönse"
                        },
                        new
                        {
                            Id = 98,
                            Force = 462,
                            Name = "Kannan Kumar(Salem)"
                        },
                        new
                        {
                            Id = 99,
                            Force = 1526,
                            Name = "Kakeda Toshimune"
                        },
                        new
                        {
                            Id = 100,
                            Force = 1992,
                            Name = "Kaneko Ietada"
                        },
                        new
                        {
                            Id = 101,
                            Force = 1923,
                            Name = "Katagiri Katsumoto"
                        },
                        new
                        {
                            Id = 102,
                            Force = 1913,
                            Name = "Katakura Kojūro"
                        },
                        new
                        {
                            Id = 103,
                            Force = 452,
                            Name = "Katakura Shigenaga"
                        },
                        new
                        {
                            Id = 104,
                            Force = 1510,
                            Name = "Kataoka Mitsumasa"
                        },
                        new
                        {
                            Id = 105,
                            Force = 682,
                            Name = "Katō Kiyomasa"
                        },
                        new
                        {
                            Id = 106,
                            Force = 1519,
                            Name = "Kawakami Gensai"
                        },
                        new
                        {
                            Id = 107,
                            Force = 1817,
                            Name = "Kido Takayoshi"
                        },
                        new
                        {
                            Id = 108,
                            Force = 964,
                            Name = "Kikkawa Hiroie"
                        },
                        new
                        {
                            Id = 109,
                            Force = 1516,
                            Name = "Kimotsuki Kanetsugu"
                        },
                        new
                        {
                            Id = 110,
                            Force = 1894,
                            Name = "Kitamura Kansuke"
                        },
                        new
                        {
                            Id = 111,
                            Force = 1851,
                            Name = "Kobayakawa Hideaki"
                        },
                        new
                        {
                            Id = 112,
                            Force = 1824,
                            Name = "Kobayakawa Hidekane"
                        },
                        new
                        {
                            Id = 113,
                            Force = 1152,
                            Name = "Kobayakawa Takakage"
                        },
                        new
                        {
                            Id = 114,
                            Force = 635,
                            Name = "Konishi Yukinaga"
                        },
                        new
                        {
                            Id = 115,
                            Force = 1258,
                            Name = "Kojima Toyoharu"
                        },
                        new
                        {
                            Id = 116,
                            Force = 1056,
                            Name = "Kuroda Kanbei"
                        },
                        new
                        {
                            Id = 117,
                            Force = 760,
                            Name = "Kuroda Kiyotaka"
                        },
                        new
                        {
                            Id = 118,
                            Force = 1514,
                            Name = "Kusunoki Masashige"
                        },
                        new
                        {
                            Id = 119,
                            Force = 568,
                            Name = "Kuwana Tarozaemon"
                        },
                        new
                        {
                            Id = 120,
                            Force = 1256,
                            Name = "Kumagai Naozane"
                        },
                        new
                        {
                            Id = 121,
                            Force = 687,
                            Name = "Maeda Keiji"
                        },
                        new
                        {
                            Id = 122,
                            Force = 482,
                            Name = "Maeda Matsu"
                        },
                        new
                        {
                            Id = 123,
                            Force = 181,
                            Name = "Maeda Nagatane"
                        },
                        new
                        {
                            Id = 124,
                            Force = 560,
                            Name = "Maeda Toshiie"
                        },
                        new
                        {
                            Id = 125,
                            Force = 1403,
                            Name = "Maeda Toshinaga"
                        },
                        new
                        {
                            Id = 126,
                            Force = 1745,
                            Name = "Maeda Toshitsune"
                        },
                        new
                        {
                            Id = 127,
                            Force = 694,
                            Name = "Magome Kageyu"
                        },
                        new
                        {
                            Id = 128,
                            Force = 627,
                            Name = "Manabe Akifusa"
                        },
                        new
                        {
                            Id = 129,
                            Force = 829,
                            Name = "Matsudaira Katamori"
                        },
                        new
                        {
                            Id = 130,
                            Force = 791,
                            Name = "Matsudaira Nobutsuna"
                        },
                        new
                        {
                            Id = 131,
                            Force = 136,
                            Name = "Matsudaira Nobuyasu"
                        },
                        new
                        {
                            Id = 132,
                            Force = 1562,
                            Name = "Matsudaira Higo no Kami Katamori"
                        },
                        new
                        {
                            Id = 133,
                            Force = 328,
                            Name = "Matsudaira Sadanobu"
                        },
                        new
                        {
                            Id = 134,
                            Force = 1003,
                            Name = "Matsudaira Tadayoshi"
                        },
                        new
                        {
                            Id = 135,
                            Force = 337,
                            Name = "Matsudaira Teru"
                        },
                        new
                        {
                            Id = 136,
                            Force = 1401,
                            Name = "Matsunaga Hisahide"
                        },
                        new
                        {
                            Id = 137,
                            Force = 644,
                            Name = "Matsunaga Hisamichi"
                        },
                        new
                        {
                            Id = 138,
                            Force = 1007,
                            Name = "Matsuo Bashō"
                        },
                        new
                        {
                            Id = 139,
                            Force = 1435,
                            Name = "Matsudaira Motoyasu"
                        },
                        new
                        {
                            Id = 140,
                            Force = 1436,
                            Name = "Minamoto no Mitsunaka"
                        },
                        new
                        {
                            Id = 141,
                            Force = 729,
                            Name = "Minamoto no Yoshiie"
                        },
                        new
                        {
                            Id = 142,
                            Force = 31,
                            Name = "Minamoto no Yoshimitsu"
                        },
                        new
                        {
                            Id = 143,
                            Force = 1023,
                            Name = "Minamoto no Yoshinaka"
                        },
                        new
                        {
                            Id = 144,
                            Force = 1497,
                            Name = "Minamoto no Yoshitomo"
                        },
                        new
                        {
                            Id = 145,
                            Force = 196,
                            Name = "Minamoto no Yoshitsune"
                        },
                        new
                        {
                            Id = 146,
                            Force = 417,
                            Name = "Minamoto no Tameyoshi"
                        },
                        new
                        {
                            Id = 147,
                            Force = 1290,
                            Name = "Minamoto no Yorimasa"
                        },
                        new
                        {
                            Id = 148,
                            Force = 186,
                            Name = "Minamoto no Yorimitsu"
                        },
                        new
                        {
                            Id = 149,
                            Force = 523,
                            Name = "Minamoto no Yoritomo"
                        },
                        new
                        {
                            Id = 150,
                            Force = 656,
                            Name = "Minamoto no Noriyori"
                        },
                        new
                        {
                            Id = 151,
                            Force = 597,
                            Name = "Minoro Takashi"
                        },
                        new
                        {
                            Id = 152,
                            Force = 525,
                            Name = "Miura Anjin"
                        },
                        new
                        {
                            Id = 153,
                            Force = 376,
                            Name = "Miura Yoshimoto"
                        },
                        new
                        {
                            Id = 154,
                            Force = 1970,
                            Name = "Miyamoto Musashi"
                        },
                        new
                        {
                            Id = 155,
                            Force = 1660,
                            Name = "Miyoshi Chōkei"
                        },
                        new
                        {
                            Id = 156,
                            Force = 162,
                            Name = "Miyoshi Kazuhide"
                        },
                        new
                        {
                            Id = 157,
                            Force = 1499,
                            Name = "Miyoshi Masaga"
                        },
                        new
                        {
                            Id = 158,
                            Force = 1066,
                            Name = "Miyoshi Masayasu"
                        },
                        new
                        {
                            Id = 159,
                            Force = 1203,
                            Name = "Miyoshi Moriyata"
                        },
                        new
                        {
                            Id = 160,
                            Force = 1611,
                            Name = "Miyoshi Nagayuki"
                        },
                        new
                        {
                            Id = 161,
                            Force = 700,
                            Name = "Miyoshi Yoshitsugu"
                        },
                        new
                        {
                            Id = 162,
                            Force = 1091,
                            Name = "Mizuno Tadakuni"
                        },
                        new
                        {
                            Id = 163,
                            Force = 1073,
                            Name = "Moniwa Yoshinao"
                        },
                        new
                        {
                            Id = 164,
                            Force = 760,
                            Name = "Mōri Motonari"
                        },
                        new
                        {
                            Id = 165,
                            Force = 65,
                            Name = "Mōri Nagasada"
                        },
                        new
                        {
                            Id = 166,
                            Force = 1754,
                            Name = "Mori Nagayoshi"
                        },
                        new
                        {
                            Id = 167,
                            Force = 436,
                            Name = "Mōri Okimoto"
                        },
                        new
                        {
                            Id = 168,
                            Force = 1027,
                            Name = "Mori Ranmaru"
                        },
                        new
                        {
                            Id = 169,
                            Force = 151,
                            Name = "Mōri Takamoto"
                        },
                        new
                        {
                            Id = 170,
                            Force = 1413,
                            Name = "Mori Tadamasa"
                        },
                        new
                        {
                            Id = 171,
                            Force = 552,
                            Name = "Mōri Terumoto"
                        },
                        new
                        {
                            Id = 172,
                            Force = 1479,
                            Name = "Mori Yoshinari"
                        },
                        new
                        {
                            Id = 173,
                            Force = 800,
                            Name = "Murai Sadakatsu"
                        },
                        new
                        {
                            Id = 174,
                            Force = 198,
                            Name = "Nagakura Shinpachi"
                        },
                        new
                        {
                            Id = 175,
                            Force = 1248,
                            Name = "Nagao Harukage"
                        },
                        new
                        {
                            Id = 176,
                            Force = 199,
                            Name = "Nagao Kagenobu"
                        },
                        new
                        {
                            Id = 177,
                            Force = 637,
                            Name = "Nagao Masakage"
                        },
                        new
                        {
                            Id = 178,
                            Force = 1323,
                            Name = "Nagao Tamekage"
                        },
                        new
                        {
                            Id = 179,
                            Force = 963,
                            Name = "Nakagawa Kiyohide"
                        },
                        new
                        {
                            Id = 180,
                            Force = 1432,
                            Name = "Nakaoka Shintarō"
                        },
                        new
                        {
                            Id = 181,
                            Force = 1199,
                            Name = "Naoe Kagetsuna"
                        },
                        new
                        {
                            Id = 182,
                            Force = 1418,
                            Name = "Naoe Kanetsugu"
                        },
                        new
                        {
                            Id = 183,
                            Force = 1700,
                            Name = "Narita Kaihime"
                        },
                        new
                        {
                            Id = 184,
                            Force = 69,
                            Name = "Nene"
                        },
                        new
                        {
                            Id = 185,
                            Force = 85,
                            Name = "Nihonmatsu Yoshitsugu"
                        },
                        new
                        {
                            Id = 186,
                            Force = 309,
                            Name = "Niimi Nishiki"
                        },
                        new
                        {
                            Id = 187,
                            Force = 1757,
                            Name = "Niiro Tadamoto"
                        },
                        new
                        {
                            Id = 188,
                            Force = 334,
                            Name = "Niwa Nagahide"
                        },
                        new
                        {
                            Id = 189,
                            Force = 362,
                            Name = "Niwa Nagashige"
                        },
                        new
                        {
                            Id = 190,
                            Force = 175,
                            Name = "Oda Hiroyoshi"
                        },
                        new
                        {
                            Id = 191,
                            Force = 1286,
                            Name = "Oda Nobuhide"
                        },
                        new
                        {
                            Id = 192,
                            Force = 158,
                            Name = "Oda Nobukata"
                        },
                        new
                        {
                            Id = 193,
                            Force = 496,
                            Name = "Oda Nobukiyo"
                        },
                        new
                        {
                            Id = 194,
                            Force = 1017,
                            Name = "Oda Nobunaga"
                        },
                        new
                        {
                            Id = 195,
                            Force = 287,
                            Name = "Oda Nobutada"
                        },
                        new
                        {
                            Id = 196,
                            Force = 294,
                            Name = "Oda Nobutomo"
                        },
                        new
                        {
                            Id = 197,
                            Force = 761,
                            Name = "Oda Nobukatsu"
                        },
                        new
                        {
                            Id = 198,
                            Force = 1600,
                            Name = "Oda Nobuyasu"
                        },
                        new
                        {
                            Id = 199,
                            Force = 472,
                            Name = "Ogasawara Shōsai"
                        },
                        new
                        {
                            Id = 200,
                            Force = 1647,
                            Name = "Ōishi Kuranosuke"
                        },
                        new
                        {
                            Id = 201,
                            Force = 174,
                            Name = "Okada Izō"
                        },
                        new
                        {
                            Id = 202,
                            Force = 772,
                            Name = "Judge Ooka"
                        },
                        new
                        {
                            Id = 203,
                            Force = 699,
                            Name = "Ōta Dōkan"
                        },
                        new
                        {
                            Id = 204,
                            Force = 721,
                            Name = "Ōtani Yoshitsugu"
                        },
                        new
                        {
                            Id = 205,
                            Force = 358,
                            Name = "Ōtani Yoshiharu"
                        },
                        new
                        {
                            Id = 206,
                            Force = 695,
                            Name = "Ōtomo Sōrin"
                        },
                        new
                        {
                            Id = 207,
                            Force = 549,
                            Name = "Okita Sōji"
                        },
                        new
                        {
                            Id = 208,
                            Force = 1730,
                            Name = "Ōkubo Toshimichi"
                        },
                        new
                        {
                            Id = 209,
                            Force = 1823,
                            Name = "OkuNameiya Masaie"
                        },
                        new
                        {
                            Id = 210,
                            Force = 1363,
                            Name = "Ōuchi Yoshitaka"
                        },
                        new
                        {
                            Id = 211,
                            Force = 1806,
                            Name = "Omy Yoshika"
                        },
                        new
                        {
                            Id = 212,
                            Force = 420,
                            Name = "Pore Sufi"
                        },
                        new
                        {
                            Id = 213,
                            Force = 1830,
                            Name = "Reizei Takatoyo"
                        },
                        new
                        {
                            Id = 214,
                            Force = 910,
                            Name = "Rokkaku Sadayori"
                        },
                        new
                        {
                            Id = 215,
                            Force = 1922,
                            Name = "Rokkaku Yoshiharu"
                        },
                        new
                        {
                            Id = 216,
                            Force = 532,
                            Name = "Rokkaku Yoshikata"
                        },
                        new
                        {
                            Id = 217,
                            Force = 432,
                            Name = "Rusu Masakage"
                        },
                        new
                        {
                            Id = 218,
                            Force = 1554,
                            Name = "Ryūzōji Takanobu"
                        },
                        new
                        {
                            Id = 219,
                            Force = 367,
                            Name = "Saigo Kiyokazu"
                        },
                        new
                        {
                            Id = 220,
                            Force = 1887,
                            Name = "Saigō Masako"
                        },
                        new
                        {
                            Id = 221,
                            Force = 37,
                            Name = "Sagara Taketō"
                        },
                        new
                        {
                            Id = 222,
                            Force = 1299,
                            Name = "Saigō Takamori"
                        },
                        new
                        {
                            Id = 223,
                            Force = 523,
                            Name = "Saigo Yoshikatsu"
                        },
                        new
                        {
                            Id = 224,
                            Force = 1283,
                            Name = "Saitō Dōsan"
                        },
                        new
                        {
                            Id = 225,
                            Force = 1591,
                            Name = "Saitō Hajime"
                        },
                        new
                        {
                            Id = 226,
                            Force = 24,
                            Name = "Saito Musashibō Benkei"
                        },
                        new
                        {
                            Id = 227,
                            Force = 1158,
                            Name = "Saitō Yoshitatsu"
                        },
                        new
                        {
                            Id = 228,
                            Force = 1727,
                            Name = "Sakai Tadakiyo"
                        },
                        new
                        {
                            Id = 229,
                            Force = 1332,
                            Name = "Sakai Tadashige"
                        },
                        new
                        {
                            Id = 230,
                            Force = 822,
                            Name = "Sakai Tadatsugu"
                        },
                        new
                        {
                            Id = 231,
                            Force = 314,
                            Name = "Sakai Tadayo"
                        },
                        new
                        {
                            Id = 232,
                            Force = 946,
                            Name = "Sakakibara Yasumasa"
                        },
                        new
                        {
                            Id = 233,
                            Force = 1226,
                            Name = "Sakamoto Ryōma"
                        },
                        new
                        {
                            Id = 234,
                            Force = 259,
                            Name = "Sakuma Morimasa"
                        },
                        new
                        {
                            Id = 235,
                            Force = 1577,
                            Name = "Sakuma Nobumori"
                        },
                        new
                        {
                            Id = 236,
                            Force = 1841,
                            Name = "Sanada Akihime"
                        },
                        new
                        {
                            Id = 237,
                            Force = 816,
                            Name = "Sanada Komatsuhime"
                        },
                        new
                        {
                            Id = 238,
                            Force = 326,
                            Name = "Sanada Masayuki"
                        },
                        new
                        {
                            Id = 239,
                            Force = 1384,
                            Name = "Sanada Nobuyuki"
                        },
                        new
                        {
                            Id = 240,
                            Force = 461,
                            Name = "Sanada Yukimura"
                        },
                        new
                        {
                            Id = 241,
                            Force = 854,
                            Name = "Sasaki Kojirō"
                        },
                        new
                        {
                            Id = 242,
                            Force = 1518,
                            Name = "Sassa Narimasa"
                        },
                        new
                        {
                            Id = 243,
                            Force = 1727,
                            Name = "Sasuke Sarutobi"
                        },
                        new
                        {
                            Id = 244,
                            Force = 1433,
                            Name = "Serizawa Kamo"
                        },
                        new
                        {
                            Id = 245,
                            Force = 242,
                            Name = "Shibata Katsuie"
                        },
                        new
                        {
                            Id = 246,
                            Force = 1784,
                            Name = "Shima Sakon"
                        },
                        new
                        {
                            Id = 247,
                            Force = 959,
                            Name = "Shimada Ichirō"
                        },
                        new
                        {
                            Id = 248,
                            Force = 1676,
                            Name = "Shimazu Katsuhisa"
                        },
                        new
                        {
                            Id = 249,
                            Force = 464,
                            Name = "Shimazu Tadahisa"
                        },
                        new
                        {
                            Id = 250,
                            Force = 1463,
                            Name = "Shimazu Tadatsune"
                        },
                        new
                        {
                            Id = 251,
                            Force = 969,
                            Name = "Shimazu Tadayoshi"
                        },
                        new
                        {
                            Id = 252,
                            Force = 1323,
                            Name = "Shimazu Takahisa"
                        },
                        new
                        {
                            Id = 253,
                            Force = 1469,
                            Name = "Shimazu Toyohisa"
                        },
                        new
                        {
                            Id = 254,
                            Force = 61,
                            Name = "Shimazu Yoshihiro"
                        },
                        new
                        {
                            Id = 255,
                            Force = 222,
                            Name = "Shimazu Yoshihisa"
                        },
                        new
                        {
                            Id = 256,
                            Force = 1194,
                            Name = "Shindou Hiroshii"
                        },
                        new
                        {
                            Id = 257,
                            Force = 880,
                            Name = "Sogo Nagayasu"
                        },
                        new
                        {
                            Id = 258,
                            Force = 1671,
                            Name = "Sue Yoshitaka"
                        },
                        new
                        {
                            Id = 259,
                            Force = 566,
                            Name = "Tachibana Muneshige"
                        },
                        new
                        {
                            Id = 260,
                            Force = 152,
                            Name = "Tachibana Dōsetsu"
                        },
                        new
                        {
                            Id = 261,
                            Force = 584,
                            Name = "Tachibana Ginchiyo"
                        },
                        new
                        {
                            Id = 262,
                            Force = 1994,
                            Name = "Taigen Sessai"
                        },
                        new
                        {
                            Id = 263,
                            Force = 166,
                            Name = "Taira no Kiyomori"
                        },
                        new
                        {
                            Id = 264,
                            Force = 740,
                            Name = "Taira Masakado"
                        },
                        new
                        {
                            Id = 265,
                            Force = 366,
                            Name = "Takahashi Shigetane"
                        },
                        new
                        {
                            Id = 266,
                            Force = 1526,
                            Name = "Takenaka Shigeharu"
                        },
                        new
                        {
                            Id = 267,
                            Force = 1785,
                            Name = "Takasugi Shinsaku"
                        },
                        new
                        {
                            Id = 268,
                            Force = 550,
                            Name = "Takayama Justo"
                        },
                        new
                        {
                            Id = 269,
                            Force = 790,
                            Name = "Takayama Ukon"
                        },
                        new
                        {
                            Id = 270,
                            Force = 340,
                            Name = "Takechi Hanpeita"
                        },
                        new
                        {
                            Id = 271,
                            Force = 1155,
                            Name = "Takeda Katsuyori"
                        },
                        new
                        {
                            Id = 272,
                            Force = 1011,
                            Name = "Takeda Nobukatsu"
                        },
                        new
                        {
                            Id = 273,
                            Force = 1847,
                            Name = "Takeda Nobushige"
                        },
                        new
                        {
                            Id = 274,
                            Force = 1137,
                            Name = "Takeda Shingen"
                        },
                        new
                        {
                            Id = 275,
                            Force = 1464,
                            Name = "Takenaka Hanbei"
                        },
                        new
                        {
                            Id = 276,
                            Force = 1455,
                            Name = "Tani Tadasumi"
                        },
                        new
                        {
                            Id = 277,
                            Force = 1605,
                            Name = "Tōdō Takatora"
                        },
                        new
                        {
                            Id = 278,
                            Force = 555,
                            Name = "Toki Yorinari"
                        },
                        new
                        {
                            Id = 279,
                            Force = 362,
                            Name = "Tochimitsu Gantyoki"
                        },
                        new
                        {
                            Id = 280,
                            Force = 689,
                            Name = "Tokugawa Ieyasu"
                        },
                        new
                        {
                            Id = 281,
                            Force = 1244,
                            Name = "Tokugawa Hidetada"
                        },
                        new
                        {
                            Id = 282,
                            Force = 932,
                            Name = "Tokugawa Nariaki"
                        },
                        new
                        {
                            Id = 283,
                            Force = 398,
                            Name = "Tokugawa Yoshinobu"
                        },
                        new
                        {
                            Id = 284,
                            Force = 1532,
                            Name = "Torii Mototada"
                        },
                        new
                        {
                            Id = 285,
                            Force = 1337,
                            Name = "Toyotomi Hidenaga"
                        },
                        new
                        {
                            Id = 286,
                            Force = 1207,
                            Name = "Toyotomi Hideyoshi"
                        },
                        new
                        {
                            Id = 287,
                            Force = 1955,
                            Name = "Toyotomi Hideyori"
                        },
                        new
                        {
                            Id = 288,
                            Force = 1525,
                            Name = "Tozuka Tadaharu"
                        },
                        new
                        {
                            Id = 289,
                            Force = 397,
                            Name = "Tsukahara Bokuden"
                        },
                        new
                        {
                            Id = 290,
                            Force = 1005,
                            Name = "Uesugi Kagekatsu"
                        },
                        new
                        {
                            Id = 291,
                            Force = 55,
                            Name = "Uesugi Kagetora"
                        },
                        new
                        {
                            Id = 292,
                            Force = 478,
                            Name = "Uesugi Kenshin"
                        },
                        new
                        {
                            Id = 293,
                            Force = 1246,
                            Name = "Ujiie Naotomo"
                        },
                        new
                        {
                            Id = 294,
                            Force = 464,
                            Name = "Ukita Naoie"
                        },
                        new
                        {
                            Id = 295,
                            Force = 1732,
                            Name = "Ukita Okiie"
                        },
                        new
                        {
                            Id = 296,
                            Force = 103,
                            Name = "Umezawa Michiharu"
                        },
                        new
                        {
                            Id = 297,
                            Force = 1418,
                            Name = "Usami Sadamitsu"
                        },
                        new
                        {
                            Id = 298,
                            Force = 360,
                            Name = "Uyama Hisanobu"
                        },
                        new
                        {
                            Id = 299,
                            Force = 1833,
                            Name = "Wada Shinsuke"
                        },
                        new
                        {
                            Id = 300,
                            Force = 666,
                            Name = "Watanabe Kazan"
                        },
                        new
                        {
                            Id = 301,
                            Force = 180,
                            Name = "Watanabe no Tsuna"
                        },
                        new
                        {
                            Id = 302,
                            Force = 600,
                            Name = "Yasumero Kenshin"
                        },
                        new
                        {
                            Id = 303,
                            Force = 604,
                            Name = "Yagyū Jūbei Mitsuyoshi"
                        },
                        new
                        {
                            Id = 304,
                            Force = 454,
                            Name = "Yagyū Munenori"
                        },
                        new
                        {
                            Id = 305,
                            Force = 1389,
                            Name = "Yamauchi Kazutoyo"
                        },
                        new
                        {
                            Id = 306,
                            Force = 683,
                            Name = "Yamada Arinaga"
                        },
                        new
                        {
                            Id = 307,
                            Force = 1859,
                            Name = "Yamada Arinobu"
                        },
                        new
                        {
                            Id = 308,
                            Force = 195,
                            Name = "Yamada Nagamasa"
                        },
                        new
                        {
                            Id = 309,
                            Force = 1123,
                            Name = "Yamagata Masakage"
                        },
                        new
                        {
                            Id = 310,
                            Force = 767,
                            Name = "Yamakawa Hiroshi"
                        },
                        new
                        {
                            Id = 311,
                            Force = 996,
                            Name = "Yamakawa Kenjirō"
                        },
                        new
                        {
                            Id = 312,
                            Force = 1026,
                            Name = "Yamakawa Naoe"
                        },
                        new
                        {
                            Id = 313,
                            Force = 553,
                            Name = "Yamanaka Yukimori"
                        },
                        new
                        {
                            Id = 314,
                            Force = 247,
                            Name = "Yamanami Keisuke"
                        },
                        new
                        {
                            Id = 315,
                            Force = 1041,
                            Name = "Yamaoka Tesshū"
                        },
                        new
                        {
                            Id = 316,
                            Force = 506,
                            Name = "Yanagawa Kenzaburo"
                        },
                        new
                        {
                            Id = 317,
                            Force = 1559,
                            Name = "Yanagisawa Yoshiyasu"
                        },
                        new
                        {
                            Id = 318,
                            Force = 1698,
                            Name = "Yonekura Shigetsugu"
                        },
                        new
                        {
                            Id = 319,
                            Force = 1831,
                            Name = "Yūki Hideyasu"
                        },
                        new
                        {
                            Id = 320,
                            Force = 477,
                            Name = "Yasuke"
                        });
                });

            modelBuilder.Entity("ArtMartialSamourai", b =>
                {
                    b.HasOne("BO.ArtMartial", null)
                        .WithMany()
                        .HasForeignKey("ArtMartialsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BO.Samourai", null)
                        .WithMany()
                        .HasForeignKey("SamouraisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BO.Samourai", b =>
                {
                    b.HasOne("BO.Arme", "Arme")
                        .WithMany()
                        .HasForeignKey("ArmeId");

                    b.Navigation("Arme");
                });
#pragma warning restore 612, 618
        }
    }
}
